Większe przyciski na prototypie
iiuni/projektzapisy pull request #1002
Opened 2020-11-04 22:47 UTC by Piotr610

1. Zmienione stare ikony z przycisków na ikony z Font Awesome.
1. Zwiększony rozmiar przycisków. Teraz również zawijają się gdy nie mieszczą się na termie. Na dużych ekranach są one umieszczane pionowo, a na małych poziomo i są one większe niż na dużych ekranach.
1. Zmienione ikony w legendzie pod prototypem na aktualne.
Fixes #967

2020-11-05 12:57 UTC, jasiekmarc requested changes
Fajnie.

Jakby Pan mógł do opisu PR-a wrzucić screeny przed i po zmianach.
Każdy ciekawy może sobie wtedy zajrzeć i nie musi uruchamiać kodu sam.

2020-11-05 12:57 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +library.add(faCarSide, faThumbtack, faBan, faPencilAlt);
To chyba nie jest potrzebne. Można zrobić tak, jak robiliśmy to wcześniej.

2020-11-05 12:57 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  align-content: flex-start;
Zależało by mi na eleganckim i czytelnym rozwiązaniu. Wydaje mi się, że nie ma istotnego powodu, dla którego te guziki mają być na dużych ekranach pozycjonowane za pomocą _Flex_, a na małych za pomocą _Grid_. Można użyć _Grid_ i tu i tam.

Elegancki CSS powinien w `@media` tylko to, co faktycznie się zmienia na małych ekranach.

2020-11-05 12:57 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +@media (max-width: 992px) {
Tu trzeba napisać komentarz, skąd się bierze liczba 992px.

Gdy ktoś będzie aktualizował Boostrapa i w nowej wersji będzie — powiedzmy — 927px, żeby miał szansę to znaleźć.

2020-11-05 17:53 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +library.add(faCarSide, faThumbtack, faBan, faPencilAlt);
Nie jestem pewny jak to było robione wcześniej, ale ten sposób na ładowanie ikon jest proponowany przed dokumentację.

2020-11-05 17:59 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +@media (max-width: 992px) {
To jest ten sam warunek do wyświetlania dni planu jeden pod drugim, a nie obok siebie. Jest to w pliku `zapisy/apps/enrollment/timetable/assets/components/SimpleTimetable.vue`.

2020-11-05 19:37 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  align-content: flex-start;
Już zrobiłem porządki w tym CSS'ie. Zdecydowałem się na użycie _Flex_ zamiast _Grid_ (już to zmieniłem dla małych ekranów), ponieważ nie podoba mi się zachowanie _Grida_. Te powyższe linijki natomiast, to "workaround" dla błędu, który sprawiał, że tło się nie rozszerzało na zawinięte przyciski.

2020-11-07 12:06 UTC, jasiekmarc requested changes
Mam dwie uwagi do wyglądu tego.

1. Pozioma pinezka zmienia znaczenie z przypinania na odpinanie (czyli na odwrotną operację). Nie jestem pewien, że powinniśmy tak ludzi zaskakiwać. Mógłby pan może spróbować, czy pinezka obrócona o 45° wygląda przyzwoicie?

2. Te ikonki (widać to na screenie z dużych ekranów) są niewyśrodkowane. To trochę nieporządnie wygląda.

2020-11-07 12:06 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +    position: relative;
Czemu dla małych ekranów jest `position: relative`?

2020-11-07 12:06 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  align-content: flex-start;
To proszę mi powiedzieć, co jest niedobrego w tym Gridzie?

No i taki _workaround_ musi być opisany w komentarzu — najlepiej z linkiem do jakiegoś StackOverflow, z którego pan to wziął.

2020-11-16 19:59 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +library.add(faCarSide, faThumbtack, faBan, faPencilAlt);
Już to zmieniłem na tak jak to było wcześniej robione.

2020-11-16 20:00 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +@media (max-width: 992px) {
Dodałem komentarz do tego.

2020-11-16 23:38 UTC, Piotr610 commented
Zmieniłem już wygląd ikon przypinania i odpinania. Tera wyglądają tak:
![pin_new](https://user-images.githubusercontent.com/45185992/99320977-12fc4100-286d-11eb-9d60-98a32d5546a3.jpg)
![unpin_new](https://user-images.githubusercontent.com/45185992/99320997-1a234f00-286d-11eb-8eab-48c4079baea1.jpg)
Oraz zaktualizowałem legendę: 
![legenda_nowa2](https://user-images.githubusercontent.com/45185992/99321011-227b8a00-286d-11eb-9d66-73ff83cc5d03.jpg)

2020-11-21 00:08 UTC, Piotr610 commented
1. Zmiana wyglądu i zachowania przycisków na dużych ekranach. Teraz bardziej przypominają stare przyciski, są względem nich niewiele większe, nie zawijają się.
1. Na małych ekranach są większe, domyślnie ustawiane poziomo, zawijają się, pozycjonowanie absolutne. 
Duże ekrany:
![auto_big](https://user-images.githubusercontent.com/45185992/99861271-e1011c80-2b95-11eb-8443-c4b41d68ec41.jpg)
![pin_enroll_big](https://user-images.githubusercontent.com/45185992/99861273-e2324980-2b95-11eb-970c-69bde7ecaf13.jpg)
![small_term_big](https://user-images.githubusercontent.com/45185992/99861276-e2cae000-2b95-11eb-9711-43341096399a.jpg)
![unenroll_big](https://user-images.githubusercontent.com/45185992/99861277-e2cae000-2b95-11eb-8765-7f40749ee420.jpg)
![unpin_big](https://user-images.githubusercontent.com/45185992/99861278-e3637680-2b95-11eb-9cc0-376b3c0eae2b.jpg)
Małe ekrany: 
![auto_small](https://user-images.githubusercontent.com/45185992/99861291-efe7cf00-2b95-11eb-99c3-f8a4ef039ac8.jpg)
![pin_enroll_small](https://user-images.githubusercontent.com/45185992/99861294-f0806580-2b95-11eb-9e58-e38f9af69833.jpg)
![unenroll_small](https://user-images.githubusercontent.com/45185992/99861295-f118fc00-2b95-11eb-9e62-815ac3f2c3b5.jpg)
![unpin_small](https://user-images.githubusercontent.com/45185992/99861297-f118fc00-2b95-11eb-9c9b-0bd3d999c556.jpg)
![wrapped_small](https://user-images.githubusercontent.com/45185992/99861299-f118fc00-2b95-11eb-921a-3eed16afc83a.jpg)

2020-11-21 11:50 UTC, jasiekmarc reviewed
No dobra, wygląda to teraz całkiem ładnie. Proszę tylko wywalić te prefiksy.

2020-11-21 11:50 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  -o-transform: rotate(45deg);
To nie powinno być potrzebne. PostCSS sam dodaje takie mądrości.

2020-11-21 13:56 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  -o-transform: rotate(45deg);
To jest potrzebne do obrócenia pinezki o 45°, ponieważ Font Awesome sam implementuje obroty jedynie 90°, 180° i 270°.

2020-11-21 13:57 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  -o-transform: rotate(45deg);
Mam na myśli _vendor prefixes_.

2020-11-21 14:48 UTC, Piotr610 commented on zapisy/apps/enrollment/timetable/assets/components/TermControls.vue
> +  -o-transform: rotate(45deg);
Już usunięte.

2021-02-07 14:39 UTC, merged