Efekty kształcenia
iiuni/projektzapisy pull request #1015
Opened 2021-01-25 19:54 UTC by Piotr610

1. Dodanie aplikacji _Effects_, która przetwarza zrealizowane efekty na podstawie kursów ukończonych przez studenta.
1. Dodanie odpowiednich funkcji do Serializera oraz Wrappera API, służących do dodawania ukończonych przez studenta kursów.
1. Wyświetlanie zrealizowanych efektów przez studenta w widoku "Moje studia".

2021-01-25 21:39 UTC, jasiekmarc requested changes
Świetnie!

Widać, że to całe zadanie mieści się w dwustu linijkach, a uszczęśliwi wielu studentów.

Zostawiłem parę drobnych uwag.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/api/rest/v1/views.py
> +    # filterset_fields = ['student']
Być może miałoby sens filtrowanie po `course__semester`, żeby móc wyświetlić wszystkie rekordy z odpowiedniego (np. aktualnego) semestru.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/effects/models.py
> +    course = models.ForeignKey(CourseInstance, on_delete=models.CASCADE)
A tu nie miało być jeszcze `ForeignKey` do programu studiów?

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/effects/models.py
> +        )
```suggestion
        completed_courses = CompletedCourses.objects.filter(student=student)
```

Django jest cwane.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/effects/models.py
> +            course_instance = CourseInstance.objects.get(id=record.course.id)
To jest niedobrze.

Chcemy, żeby każda funkcja wywoływała stałą liczbę zapytań do bazy danych — niezależnie od danych.
Tuta wykonujemy jedno zapytanie dla każdego _completed course_, oraz jeszcze jedno, żeby wyłuskać efekty.

Pierwsze zapytanie jest w ogóle zbędne, bo `record.course` zwraca nam obiekt typu `CourseInstance` (tylko niestety pod maską też robi wycieczkę do bazy danych).
Na szczęście wszystko to można załatwić dodająć `select_related` i `prefetch_related` do tego zapytania na górze.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/effects/templates/effects.html
> +</tr>
Newline.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/users/templates/users/my_profile.html
> +            {% include "effects.html" %}
Ja bym zrobił `{% include … with … %}`, żeby nie kopiować całego kontekstu do tego drugiego template'a.

2021-01-25 21:39 UTC, jasiekmarc commented on zapisy/apps/effects/models.py
> +from apps.enrollment.courses.models.course_instance import CourseInstance
Tu też chcielibyśmy porządku alfabetycznego.

2021-01-26 16:38 UTC, ldept commented on zapisy/apps/effects/models.py
> +    course = models.ForeignKey(CourseInstance, on_delete=models.CASCADE)
Nie wiem czy będzie to potrzebne.

Z tego co udało mi się znaleźć (może coś przeoczyłem) to na studiach II stopnia nie ma efektów kształcenia - są tylko wymogi dotyczące ECTSów. 

Dla studiów I stopnia efekty różnią się pomiędzy studiami licencjackimi, a inżynierskimi (na inż jest trochę więcej), ale będziemy wyświetlać tylko listę zaliczonych już efektów, a nie listę efektów które jeszcze trzeba zaliczyć.

2021-01-26 19:17 UTC, ldept commented on zapisy/apps/effects/models.py
> +            course_instance = CourseInstance.objects.get(id=record.course.id)
Zmiany w [f0833b7](https://github.com/iiuni/projektzapisy/pull/1015/commits/f0833b72673dad50b9efd88a10677113d02c501d)

2021-01-29 08:57 UTC, jasiekmarc commented on zapisy/apps/effects/models.py
> +    course = models.ForeignKey(CourseInstance, on_delete=models.CASCADE)
To jest prawda. Ma Pan rację.

Ale też myślę, że gdybyśmy chcieli dodać do aplikacji inne możliwości — takie jak zliczanie punktów ECTS dla różnych treści — to ta informacja o programie studiów mogła by się przydać.

2021-01-29 11:53 UTC, ldept commented on zapisy/apps/effects/models.py
> +    course = models.ForeignKey(CourseInstance, on_delete=models.CASCADE)
Dodałem już program i zrobiłem refaktor API dla programu i studenta.

Program w API jest teraz dostępny przez samą nazwę (stringa), tak jak było wcześniej, ale:
 

- teraz w obie strony (pobierając dane z API jak i wysyłając do API - wcześniej tylko wysyłając do API) - pobierając dane z API nie dostajemy całego obiektu Program, tylko samą nazwę e.g. `'program': "Informatyka I stopnia"`

- od razu jest walidowany (sprawdzane jest czy taki program znajduje się w naszej bazie danych). Przy braku odpowiedniego programu w bazie danych zwracany jest błąd HTTP 500 Internal Server Error,  "Program matching query does not exist"

Zmiany te są analogiczne do sposobu działania StudentRelatedField i CourseRelatedField.

Z serializera studenta zniknęło trochę kodu + zaszły zmiany w testach.

Chciałbym żeby sprawdził Pan bardziej właśnie studenta i jego testy. Starałem się zmieniać jak najmniej i zachować poprzedni charakter testów.
Większość zmian jest w tym commicie: https://github.com/iiuni/projektzapisy/pull/1015/commits/6065afc9e06539ebac9ff07525a608f12a69c22d, reszta commitów to linter i kosmetyka.

2021-02-04 20:21 UTC, jasiekmarc requested changes
Drobne zmiany w API — te z programem — mają jak najbardziej sens.

Jedyna drobnostka, jaką jeszcze trzeba poprawić, to JOIN-y w zapytaniach. Żeby pobieranie listy 1000 `CompletedCourses` przez API nie wymagało 1000 zapytań do bazy danych, tylko jednego. I podobnie z pobieraniem listy studentów.

Poza tym już wszystko gra.

2021-02-04 20:21 UTC, jasiekmarc commented on zapisy/apps/api/rest/v1/views.py
> +    queryset = CompletedCourses.objects.select_related('student')
Tu trzeba też dodać `'student__program'` do `select_related()`.

…a nawet bardziej istotne jest, by dodać to do `StudentViewSet`.

2021-02-06 14:08 UTC, jasiekmarc approved these changes
Dziękuję Panom za wykonanie zadania!

2021-02-06 14:12 UTC, merged