Adjustments in offer assignments
iiuni/projektzapisy pull request #1047
Opened 2021-07-06 10:13 UTC by mbuszka

Fix counting of hours towards pensum.
Update formatting of hours towards pensum.
Show count when a teacher is assigned to a given course multiple times.

2021-07-06 12:50 UTC, jasiekmarc requested changes
Brawo. Przebicie się przez ten kod musiało być upierdliwe. Generalnie, jak go reformowałem, chciałem, żeby było jasne, że on po prostu przesypuje dane z jednego dobrze zdefiniowanego formatu (typu danych) do drugiego. To jest szczególnie istotne, bo jak ktoś zepsuje dane w arkuszu, to musimy się umieć połapać, co nie gra.

Zostawiłem ze dwie uwagi w tym duchu.

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +                                      'hours_to_pensum_display': hours_to_pensum_display})
Na to powinniśmy moim zdaniem mieć typ.

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +                hours=assignment.hours_semester, teachers=dict())
```suggestion
                hours=assignment.hours_semester, teachers={})
```

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +        # We do not use a defaultdict since it conflicts with django templates
```suggestion
        # We do not use a defaultdict because it conflicts with django templates.
```

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +        assignments_course_info[group_type].teachers[teacher_info] = count + 1
A czy [Counter](https://docs.python.org/3/library/collections.html#collections.Counter) by nie zadziałał?

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +        # Here we prepare a display string for the hours that count towards pensum
```suggestion
        
        # We prepare a display string for the hours that count towards pensum.
```

Ten kawałek w ogóle wygląda, jakby chciał się przenieść do jakiejś małej, pomocniczej funkcji. Może do konstruktora tego typu, którego nie mamy?

Wtedy konstruktor mógłby również wykonywać ten rachunek z linijek 81-83.

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +        non_standard = False
Ja bym nadał tej zmiennej bardziej mówiącą nazwę. Na przykład `has_hours_multiplier`.

2021-07-06 12:50 UTC, jasiekmarc commented on zapisy/apps/offer/assignments/views.py
> +            hours_to_pensum_display += f"{floatformat(assignment.equivalent)}⋅"
W _f-stringach_ w Pythonie nie trzeba używać funkcji `floatformat`. Jeśli chcesz jakiegoś konkretnego formatu, to możesz go po prostu zażądać.

https://stackoverflow.com/a/50340297

2021-07-06 14:18 UTC, mbuszka commented on zapisy/apps/offer/assignments/views.py
> +        assignments_course_info[group_type].teachers[teacher_info] = count + 1
Niestety nie, ma ten sam problem co `defaultdict`: https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-variables

2021-07-06 14:28 UTC, mbuszka commented on zapisy/apps/offer/assignments/views.py
> +            hours_to_pensum_display += f"{floatformat(assignment.equivalent)}⋅"
Tutaj chciałem użyć aktualnego formatowania: zapis dziesiętny i jedna cyfra po przecinku ale tylko gdy jest potrzebna. Wydaje mi się, że formatki które podesłałeś nie dają takiej opcji (a przynajmniej nie rzuca mi się ona w oczy).

2021-07-07 11:04 UTC, jasiekmarc approved these changes

2021-07-07 11:48 UTC, merged