Change default priority for all emails, title and content for notifications
iiuni/projektzapisy pull request #1125
Opened 2021-11-07 14:46 UTC by MoloToha

2021-11-14 19:10 UTC, MoloToha commented
@mbuszka 
Maile będą wyglądać następująco:
<img width="760" alt="Screenshot_28" src="https://user-images.githubusercontent.com/5648479/141694980-7c5ba2b2-3cdf-4e2b-ab85-ceeda6806ff0.png">

2021-11-23 10:27 UTC, mbuszka requested changes
Myślę, że dobrze by było zmienić wyświetlanie reszty powiadomień tak aby każda z nich miała tytuł i treść. Wtedy będzie można stworzyć szablony tytułów w pliku https://github.com/iiuni/projektzapisy/blob/91b8920d2143f53bb984ba12699895d5695fb1d2/zapisy/apps/notifications/templates.py#L39 analogicznie do szablonów treści. Wtedy zarówno powiadomienia w aplikacji (po odpowiedniej modyfikacji ich wyświetlania) jak i w mailu będą mogły składać się z tytułu i treści, bez modyfikacji zawartości powiadomień w bazie danych.

2021-11-23 10:27 UTC, mbuszka commented on zapisy/mailer/models.py
> +        default='3',
Ten plik jest martwy i nie jest częścią systemu powiadomień, zmiany należy dokonać w https://github.com/iiuni/projektzapisy/blob/68862bf1f819bd18b753ab02a15b97ed56de7b91/zapisy/apps/news/models.py#L33

2021-11-23 10:27 UTC, mbuszka commented on zapisy/apps/notifications/tasks.py
> +EMAIL_SUBJECT_TEMPLATE = getattr(settings, "EMAIL_SUBJECT_TEMPLATE", "[ZAPISY] %s")
Nie trzymamy takich szablonów w ustawieniach, także getattr wydaje się tutaj zbędny.

2021-11-23 10:27 UTC, mbuszka commented on zapisy/apps/notifications/tasks.py
> +
To miejsce powinno się uprościć gdy wprowadzi Pan zmiany z komentarza ogólnego.

2022-01-12 12:39 UTC, mbuszka approved these changes

2022-01-24 09:38 UTC, merged