Trwałe filtry wyszukiwania
iiuni/projektzapisy pull request #1129
Opened 2021-11-12 21:16 UTC by JMendyk

Trwałe filtry wyszukiwania (patrz https://github.com/iiuni/projektzapisy/issues/1024)

Opis problemu, rozważone oraz wybrane rozwiązanie są opisane w https://hackmd.io/6tclhbJnQVq4d9TF2iwNMg.

Na całość zmian składają się pomniejsze PRy:
- https://github.com/iiuni/projektzapisy/pull/1122
- https://github.com/iiuni/projektzapisy/pull/1123
- https://github.com/iiuni/projektzapisy/pull/1124

2021-12-06 10:42 UTC, mbuszka requested changes
Dziękuję Panom, wygląda (i działa) to wszystko bardzo dobrze. Kilka drobnych uwag zostawiłem w komentarzach do konkretnych plików. Jak już zostaną rozwiązane prosiłbym też o krótki opis zmian oraz tego jak działa zarządzanie filtrami w opisie PR.

2021-12-06 10:42 UTC, mbuszka commented on zapisy/apps/enrollment/courses/assets/components/CourseList.vue
> +    const link: Element = semesterLinks[i];
Nit: Czy pętla for-of nie byłaby tutaj odpowiedniejsza

2021-12-06 10:42 UTC, mbuszka commented on zapisy/apps/enrollment/timetable/assets/components/CourseFilter.vue
> +    ];
Czy dałoby się (łatwo) generować tę listę na podstawie template'u?

2021-12-06 10:42 UTC, mbuszka commented on zapisy/apps/enrollment/timetable/assets/components/filters/LabelsFilter.vue
> +      return keys(this.allLabels) as unknown as number[];
Nit: Czy nie wystarczy tutaj `return keys(this.allLabels) as number[];`

2021-12-06 10:42 UTC, mbuszka commented on zapisy/apps/enrollment/timetable/assets/components/filters/LabelsFilter.vue
> +    });
Rozważyłbym tutaj przełączenie wartości filtrów i pojedyncze wywołanie odświeżające query string na koniec. Aktualna implementacji generuje O(n) odświeżeń adresu, co jest zauważalne przy większej ilości wybranych labelek.

2021-12-06 11:29 UTC, JMendyk commented on zapisy/apps/enrollment/timetable/assets/components/filters/LabelsFilter.vue
> +      return keys(this.allLabels) as unknown as number[];
Tak, ta konstrukcja wygląda bardzo sztucznie.

Bez `as unknown` Vetur zgłasza ostrzeżenie celem zapobiegnięcia niezamierzonej nietrywialnej zmianie informacji o typie
> Conversion of type 'string[]' to type 'number[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'string' is not comparable to type 'number'.
  Vetur(2352)

Pisząc ten kod zbyt pobieżnie zapoznałem się z jego niuansami.

Funkcja `keys` zwraca listę o elementach typu `string`, bo klucze obiektów w JS są typu `string`. Pozostałe typy są konwertowane do `string` gdy są używane na potrzeby "bycia kluczem". Jednak przykładowo Chrome w narzędziach deweloperskich wyświetlając obiekty sugeruje, że klucze są jednak liczbami :man_shrugging:.

W omawianym kodzie przyjmujemy jednak że klucze są liczbami, co jest dodatkowo wzmocnione anotacją typową `KVDict` dla `allLabels`, gdzie
```
export interface KVDict {
  [key: number]: string;
}
```

Moglibyśmy więc alternatywnie napisać (ku tej opcji się skłaniam)
```
return keys(this.allLabels).map(Numbers);
```
lub skorzystać z typu `Map<K, V>`, w którym klucze rzeczywiście są ustalonego typu, jednak praca z tą strukturą jest istotnie inna (`set`/`get` zamiast indeksowania).

2021-12-06 12:54 UTC, mbuszka commented on zapisy/apps/enrollment/timetable/assets/components/filters/LabelsFilter.vue
> +      return keys(this.allLabels) as unknown as number[];
A czy jest dla nas właściwie istotne, czy te indeksy są liczbami?

2021-12-07 06:06 UTC, lukasz05 commented on zapisy/apps/enrollment/courses/assets/components/CourseList.vue
> +    const link: Element = semesterLinks[i];
Przy próbie bezpośredniego iterowania po `semesterLinks` za pomocą for-of, Vetur zgłasza błąd:

> Type 'HTMLCollectionOf<Element>' must have a '\[Symbol.iterator]()' method that returns an iterator. Vetur(2488)

Należałoby więc utworzyć tablicę z tego obiektu za pomocą `Array.from()`:
```suggestion
  for (const link of Array.from(semesterLinks)) {
```

Nie byłem pewien czy takie rozwiązanie byłoby lepsze od zastosowania zwykłej pętli for.

2021-12-07 06:06 UTC, lukasz05 commented on zapisy/apps/enrollment/timetable/assets/components/CourseFilter.vue
> +    ];
Komponent `CourseFilter` musiałby mieć dostęp do zagnieżdżonych w swoim template komponentów. W tym celu należałoby każdemu z nich przypisać identyfikator poprzez atrybut `ref`, tak aby móc się do nich odwoływać za pomocą `this.$refs`.  

Wtedy listę `filterableProperties` można by było wygenerować następująco:

```typescript
const filterableProperties = Object.values(this.$refs).map((filter: any) => filter.property);
```

2021-12-08 14:50 UTC, mbuszka commented on zapisy/apps/enrollment/courses/assets/components/CourseList.vue
> +    const link: Element = semesterLinks[i];
Myślę, że można zostawić jak jest.

2021-12-08 14:55 UTC, mbuszka commented on zapisy/apps/enrollment/timetable/assets/components/CourseFilter.vue
> +    ];
To chyba warto tak zrobić, w kontekście deduplikacji między widokiem w courses, prototype (i pewnie niedługo też w vote).

2021-12-11 20:49 UTC, JMendyk commented on zapisy/apps/enrollment/timetable/assets/components/filters/LabelsFilter.vue
> +      return keys(this.allLabels) as unknown as number[];
Ma to znaczenie w kontekście funkcji `intersection` w `IntersectionFilter`, która używa operatora równości [SameValueZero](https://262.ecma-international.org/7.0/#sec-samevaluezero) (który patrzy m.in. na typy).

Ostatecznie wybrałem opcję z mapowaniem kluczy na wartości liczbowe w computed property: https://github.com/iiuni/projektzapisy/pull/1155.

2021-12-12 10:53 UTC, lukasz05 commented on zapisy/apps/enrollment/timetable/assets/components/CourseFilter.vue
> +    ];
Zawarłem te zmiany w PR #1156.

2021-12-17 12:58 UTC, mbuszka approved these changes
Dziękuję, wygląda to bardzo dobrze.

2022-01-03 08:56 UTC, merged