Issue 1097 - Add a view with a list of students for a course
iiuni/projektzapisy pull request #1157
Opened 2021-12-13 19:41 UTC by moalje

Resolve issue https://github.com/iiuni/projektzapisy/issues/1097
Add a view of all students enrolled and in queue for a course and each type of groups. The view is available with a "Lista" button on the course page in next to the course name, and each group section.

The view is quite similar to the one for a group. It contains a list of enrolled and queued students, a number of enrolled and queued students, the ability to send an email (hidden addresses or not) and to download a csv list.

We define that a student is enrolled in a course, if he is enrolled in any group in the course. A student is in a queue for a course, if he is in a queue for any group and is not enrolled in any group.

2021-12-17 13:44 UTC, mbuszka commented
I would suggest to modify the current view for two purposes:
- A view summarizing the state for the whole course (as i believe it works now). Available via a label in a new section above the section "Wykłady" which could also display the total count of enrolled students.
- A view for each group type (e.g. lecture, lab, exercise) with a list of enrolled students and queued-not-enrolled
I think that we could use the existing label "Niezapisanych-oczekujących" to redirect to the summaries when it exists and the label "Lista dla kursu" otherwise.

2022-01-10 10:50 UTC, mbuszka requested changes
Funkcjonalnie działa elegancko, pozostawiłem kilka komentarzy odnośnie kodu.

2022-01-10 10:50 UTC, mbuszka commented on zapisy/apps/enrollment/courses/views.py
> +    def get_group_data(group_id):
Ta funkcja nie musi być zagnieżdżona w `course_list_view` i wyciągnięcie jej na top-level oraz dodanie doc-string'a znacząco poprawi czytelność. Warto by było także zmienić ją tak aby jako parametr otrzymywała zbiór grup oraz status który nas interesuje (ENROLLED, QUEUED) i zwraca posortowaną alfabetycznie listę studentów. Moglibyśmy jej użyć zarówno tutaj jak i w `group_view` oraz generowaniu raportów csv. Dobrze byłoby ją tak napisać aby robiła tylko jedno zapytanie do bazy danych (n.p. poprzez filtrowanie z użyciem `__in`).

2022-01-10 10:50 UTC, mbuszka commented on zapisy/apps/enrollment/courses/views.py
> +    can_user_see_all_students_here = all(
Wydaje mi się, że tutaj można po prostu przyjąć, że dowolny `proper_employee` lub nauczyciel z kursu może zobaczyć listę studentów.

2022-01-10 10:50 UTC, mbuszka commented on zapisy/apps/enrollment/courses/views.py
> +        ])
Ten kawałek logiki odpowiedzialny za tworzenie listy osób niezapisanych-oczekujących warto by także wydzielić jako funkcję pomocniczą, jako, że używamy tego w generowaniu raportu csv.

2022-02-04 12:10 UTC, mbuszka requested changes
Po zmianach `group_view` przestało działać. Zostawiłem propozycję poprawek, ma ona jednak ten problem, że gdy chcemy wyświetlić informacje o grupie która nie istnieje, to dostajemy wewnętrznym błędem, a nie 404. Można to poprawić albo na poziomie `group_view` albo `get_group_data` (tam także zostawiłem komentarz).

2022-02-04 12:10 UTC, mbuszka commented on zapisy/apps/enrollment/courses/views.py
> +            continue
Dlaczego nie rzucamy tutaj wyjątkiem?

2022-02-07 09:32 UTC, mbuszka requested changes

2022-02-07 09:32 UTC, mbuszka commented on zapisy/apps/enrollment/courses/views.py
> +    return (name, [group.id for group in course.groups.all()])
Ta funkcja powinna być też sparametryzowana typem zajęć, tak samo jak wyświetlanie listy studentów w `course_list_view`. Po zmianie możnaby ją pewnie tam wykorzystać, tak aby nie duplikować kodu znajdującego listę grup.

2022-02-11 16:48 UTC, mbuszka approved these changes

2022-02-13 21:35 UTC, moalje commented
> Proszę jeszcze odświeżyć opis aby odzwierciedlał stan faktyczny i możemy mergować

Poprawiłam

2022-02-14 17:15 UTC, merged