Vote filters
iiuni/projektzapisy pull request #1164
Opened 2021-12-21 18:41 UTC by Vlad311010

2022-01-04 14:02 UTC, mbuszka commented
Please fix linter errors and failing tests before requesting a code review.

2022-01-24 10:55 UTC, mbuszka requested changes
Po merge'u zmian związanych z #1129 filtry przestały działać, proszę zbadać w czym problem.

2022-01-24 10:55 UTC, mbuszka commented on zapisy/apps/offer/vote/assets/point-counter.ts
> +}
Tutaj lepiej wykorzystać interfejs filtrów tak jak w `zapisy/apps/enrollment/courses/assets/components/CourseList.vue` linie 26 oraz 31-34 do zarządzania listą widocznych kursów

2022-01-24 10:55 UTC, mbuszka commented on zapisy/apps/offer/vote/assets/point-counter.ts
> +}
Czy nie można tutaj po prostu użyć `JSON.parse` na całej tablicy (`coursesDataStr`)

2022-01-24 10:55 UTC, mbuszka commented on zapisy/apps/offer/vote/templates/vote/form.html
> +
To proszę usunąć, zależności są dodawane przez webpack'a

2022-02-08 18:33 UTC, Vlad311010 commented
Zmieniłem sposób filtrowania. Chociaż teraz funkcja filtrowania jest wywoływana zbyt często. (ale myślę, że to nie jest problem)

2022-02-24 19:54 UTC, merged