Max number of students (issue #1135)
iiuni/projektzapisy pull request #1170
Opened 2022-01-09 21:23 UTC by akucintavalent

Resolve issue [#1135](https://github.com/iiuni/projektzapisy/issues/1135) 
Added max_number_of_students field to ThesisFormBase, which resulted in addition this field to ThesisForm and EditThesisForm. If number of selected students is greater than max_number_of_students, the form will throw validation error.
<img width="1280" src="https://user-images.githubusercontent.com/87897753/148701118-631d44bb-09a7-4550-92cb-2b9a9f85bbd7.png">
Applied migrations to add this field to the `thesis` table in the database.
Display max_number_of_students on the thesis page.
<img width="1280" src="https://user-images.githubusercontent.com/87897753/148701378-fccce862-0123-4021-bc23-ce64c3099eb8.png">
Created tests for this field. One test with valid form data and one test with not valid form data.
Fixed previous tests.

2022-01-13 18:17 UTC, mbuszka requested changes

2022-01-16 11:37 UTC, JMendyk commented on zapisy/apps/theses/templates/theses/thesis.html
> +          <th scope="row">Maskymalna liczba studentów</th>
```suggestion
          <th scope="row">Maksymalna liczba studentów</th>
```

2022-01-17 05:11 UTC, akucintavalent commented on zapisy/apps/theses/forms.py
> +        #     " dyrektora ds. dydaktycznych."),
Zrobione

2022-01-17 05:12 UTC, akucintavalent commented on zapisy/apps/theses/forms.py
> +    def clean(self):
Zrobione

2022-01-17 05:19 UTC, akucintavalent commented on zapisy/apps/theses/forms.py
> +        if 'students' in self.changed_data and len(students) > max_number_of_students:
Na razie nie rozumiem jak ta funkcja działa

2022-01-17 14:03 UTC, akucintavalent commented
@mbuszka, could you please review the code again?

2022-01-24 17:42 UTC, mbuszka approved these changes

2022-01-24 17:44 UTC, merged