Cron jobs
iiuni/projektzapisy pull request #1216
Opened 2022-03-17 15:00 UTC by latarniakonto

According to issue #986 there is a need for an automatic Django sessions cleanup service.
I was testing the problem on ii_zapisy_db_dump_2022_03_07__01_00_16_dev database backup.
Initially there are over  60k overdue entries in django_sessions database table.
After executing command `python manage.py clearsessions` manually
I went down to only 800 entries.

Therefore I created automatic clenaup service. From now on at 0:00 every Friday, special cleanup command will delete overdue Django sessions.

2022-03-29 07:50 UTC, jasiekmarc commented
Wydaje mi się, że tu nie warto pisać własnego kodu w ogóle. A szczególnie skryptu, który ma wyłącznie dodać coś do crontaba.

W nowoczesnym Linuksie warto korzystać ze wspaniałości jaką jest Systemd. Można stworzyć plik 
konfiguracyjny `.timer`, wrzucić go w odpowiedni katalog, i mamy usługę uruchamianą z taką częstotliwością, jaką sobie zażyczymy — w Systemie Zapisów robimy tak z backupami ([`backup.timer`](https://github.com/iiuni/projektzapisy/blob/master-dev/infra/playbooks/templates/backup.timer), [`backup.service`](https://github.com/iiuni/projektzapisy/blob/master-dev/infra/playbooks/templates/backup.service.j2).

2022-04-05 08:42 UTC, jasiekmarc requested changes
Duży krok w dobrym kierunku!

Wydaje mi się, że jest Pan w pewnej konfuzji, co do różnych środowisk, w których uruchamiamy System Zapisów.
Ta wirtualna maszyna „zabawkowa”, którą uruchamiamy w Vagrancie jest **tylko** po to, by na niej rozwijać kod.

W praktyce system jest uruchamiany w środowisku produkcyjnym, i to tam potrzebujemy tej usługi sprzątającej bazę danych. Zachęcam do zasymulowania sobie takiego środowiska produkcyjnego na swoim własnym komputerze: https://github.com/iiuni/projektzapisy/tree/master-dev/infra#example

2022-04-14 08:45 UTC, jasiekmarc approved these changes
Teraz wygląda to generalnie rozsądnie.

Na pewno przed zmerge'owaniem należy przetestować, tak jak wcześniej napisałem.

Ponadto (to uwaga do @lgpawel) trzeba będzie dać znać administratorowi, żeby przy następującym deploy'u uruchomił playbook konfigurujący maszynę (https://github.com/iiuni/projektzapisy/tree/master-dev/infra#configure-the-remote-machine), bo usługa jest zdefiniowana w tamtym playbooku.

2022-04-14 08:45 UTC, jasiekmarc commented on infra/playbooks/dev/services.yml
> -
Nie ma potrzeby usuwać tej linii.

2022-04-14 08:45 UTC, jasiekmarc commented on infra/playbooks/templates/django_cleanup.timer
> +WantedBy=timers.target
Nowa linia na końcu na pewno nie zaszkodzi :smile:.

2022-04-23 09:08 UTC, jasiekmarc commented on infra/readme.md
> +Database user is *fereol* as defined in `infra/playbooks/templates/env.js` however password for the database is encrypted. It will be randomly encrypted everytime we run `vagrant up`. We can retrievi
Tu jest drobna nieprawda. Hasło zmienia się tylko przy `vagrant provision`, a nie przy `vagrant up`.

Ponadto nie ma żadnej potrzeby, żeby się do niego dobierać — dlatego nie dodawałbym tej informacji do README. Django zna to hasło, więc wystarczy wejść do katalogu aplikacji i odpalić `manage.py dbshell`.

2022-05-01 18:26 UTC, latarniakonto commented on infra/readme.md
> +Database user is *fereol* as defined in `infra/playbooks/templates/env.js` however password for the database is encrypted. It will be randomly encrypted everytime we run `vagrant up`. We can retrievi
Gdy testowałem kod w środowisku developerskim to właśnie sprawdzałem jak zmienia się stan bazy danych, czy mój kod rzeczywiście usuwa te zaległe sesje. Następnie po Pana uwagach i przeniesieniu kodu do środowiska produkcyjnego również chciałem przetestować czy stan bazy danych się zmieni, czy zaległe sesje Django zostaną usunięte. Potrzebny mi był właśnie dostęp do tej bazy danych żeby to wykonać, stąd też moja wzmianka o sposobie, który wykorzystałem w README, ponieważ nie znalazłem w dostępnej dokumentacji żadnej informacji o tym. Jestem w trakcie nauki Django, więc nie znałem jeszcze tej sprytnej funkcji. Czy zatem może warto było dodać właśnie jakąś wzmiankę o tym sposobie z `manage.py dbshell`? Wydaje mi się że wiele osób, które rozwija System Zapisów w ramach przedmiotu, które tak jak ja dopiero zaczynają swoją przygodę z Django mogłoby na tym skorzystać.

2022-05-04 16:16 UTC, jasiekmarc commented on infra/readme.md
> +Database user is *fereol* as defined in `infra/playbooks/templates/env.js` however password for the database is encrypted. It will be randomly encrypted everytime we run `vagrant up`. We can retrievi
Ja bym dodał wskazówkę do Wiki.

2022-05-16 08:48 UTC, jasiekmarc commented on infra/playbooks/dev/services.yml
> +
To nie jest BARDZO ISTOTNE, ale ta linijka była w porządku. Nie potrzebujemy tych spacji.

Warto sobie skonfigurować edytor tak, żeby nie zostawiał takiego bałaganu:
https://github.com/iiuni/projektzapisy/wiki/Wskaz%C3%B3wki%3A-Konfiguracja-Edytora

2022-07-27 15:24 UTC, lgpawel approved these changes

2022-07-29 17:57 UTC, merged