Filtrowanie w statystykach
iiuni/projektzapisy pull request #1221
Opened 2022-03-23 16:43 UTC by Damian-Dziedzic

2022-04-05 11:25 UTC, lgpawel requested changes
Funkcjonalności z grubsza wyglądają OK, choć jeszcze poprosiłem o komentarz głównego zainteresowanego. Jedna rzecz w UX jest natomiast dość toporna: przy "resecie" filtrów (wyczyszczeniu pola tekstowego w przypadku nazwy przedmiotu i odptaszeniu checkboksa w przypadku obecności oczekujących studentów) strona przestaje odpowiadać na kilka niekomfortowych sekund (sprawdzane m.in. na komputerze z 16 GB RAM, choć z ok. 4 z nich zajętymi przez VirtualBoksa). Zmiana w objętości wyświetlanej strony jest oczywiście niemała, ale jednak nie uzasadnia czegoś takiego.

Dodatkowo proszę o uzupełnienie (dość precyzyjne) opisu PR. Opis issue, który PR rozwiązuje, nie musi być i zazwyczaj nie będzie wyczerpujący jako opis PR. Tu na przykład o komentarz proszą się (zwłaszcza, ale nie tylko) zmiany w pliku `zapisy/apps/statistics/templates/statistics/groups_list.html`.

2022-04-05 11:25 UTC, lgpawel commented on zapisy/apps/statistics/templates/statistics/groups_list.html
> +{% extends "statistics/base.html" %}vagrant reload
Tu chyba coś zostało wpisane do złego okna i tak zostało.

2022-04-05 11:25 UTC, lgpawel commented on zapisy/apps/statistics/views.py
> +            'number_of_waiting_students': functools.reduce(lambda acc, s: acc + s['number'], students, 0)
Wydaje mi się, że to właściwa linia do tego komentarza: w przypadku kilku liczb niezapisanych studentów (dla osobnych kategorii grup zajęciowych) suma zazwyczaj (lub wręcz zawsze) oznacza liczenie tych samych osób wiele razy) – lepsze _chyba_ byłoby branie maksimum. Przy czym w tej kwestii już poprosiłem o feedback dyrekcję i lepiej na niego poczekać.

2022-04-05 11:25 UTC, lgpawel commented on zapisy/apps/statistics/views.py
> +            'number_of_waiting_students': functools.reduce(lambda acc, s: acc + s['number'], students, 0)
Wydaje mi się, że to właściwa linia do tego komentarza: w przypadku kilku liczb niezapisanych studentów (dla osobnych kategorii grup zajęciowych) suma zazwyczaj (lub wręcz zawsze) oznacza liczenie tych samych osób wiele razy) – lepsze _chyba_ byłoby branie maksimum. Przy czym w tej kwestii już poprosiłem o feedback dyrekcję i lepiej na niego poczekać.

2022-04-06 11:04 UTC, jasiekmarc commented
>  przy "resecie" filtrów (wyczyszczeniu pola tekstowego w przypadku nazwy przedmiotu i odptaszeniu checkboksa w przypadku obecności oczekujących studentów) strona przestaje odpowiadać na kilka niekomfortowych sekund

Nie wykluczam, że powodem jest sortowanie. Nie wiem dokładnie, co Vuex robi z tymi przedmiotami po „odptaszeniu”, ale być może dodaje je po jednym i próbuje ustalić ich porządek, co by skutkowało czymś w rodzaju Insertion Sorta. Można tę hipotezę zweryfikować wyłączając sortowanie i sprawdzając „odptaszanie”.

2022-04-13 18:39 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/views.py
> +            'number_of_waiting_students': functools.reduce(lambda acc, s: acc + s['number'], students, 0)
Czy już coś wiadomo w tej sprawie? Zmienić na maksimum z listy osób? Moim zdaniem nawet jeśli w tym przypadku zliczy się osoby więcej niż raz, to nie zmieni to rezultatu. Pokazuje to duże zainteresowanie przedmiotem.

2022-04-14 07:58 UTC, lgpawel commented on zapisy/apps/statistics/views.py
> +            'number_of_waiting_students': functools.reduce(lambda acc, s: acc + s['number'], students, 0)
Najwyraźniej nie ogarnąłem czegoś w tym systemie komentarzy w code review i to, co napisałem już wiele dni temu, było widoczne tylko dla mnie :facepalm: no ale teraz już powinno być skutecznie wysłane.

2022-04-14 08:02 UTC, lgpawel commented on zapisy/apps/statistics/views.py
> +            'number_of_waiting_students': functools.reduce(lambda acc, s: acc + s['number'], students, 0)
I to nie jest prawda z tym "dużym zainteresowaniem przedmiotem" - jeśli mamy projekt A (sama pracownia), zwykły przedmiot B (zajęcia pomocnicze i wykład) oraz obowiązek C (ćwiczenia, repetytorium i wykład), i każdym jest zainteresowane dokładnie n niezapisanych osób, to sortowanie po sumie wyrzuci wyżej C (bo suma wynosi 3n), niżej B (2n) a na końcu A - a trudno twierdzić, że zainteresowanie przedmiotem jest proporcjonalne do liczby różnych rodzajów zajęć w ramach tego przedmiotu. Sumowanie po wszystkich grupach np. ćwiczeniowych i tak jest i tak ma zostać, ale doliczać do tego kolejny raz te same osoby tylko dlatego, że do przedmiotu jest repetytorium, jest bez sensu. No i głównie znajdowaniu prowadzących do zajęć pomocniczych ma to wszystko służyć, grupa wykładowa czy repetytoryjna i tak jest zawsze jedna i co do zasady obsadzona

2022-04-14 08:37 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/templates/statistics/groups_list.html
> +{% extends "statistics/base.html" %}vagrant reload
W nowym commicie zostało to już usunięte.

2022-04-15 19:08 UTC, Damian-Dziedzic commented
> `v-key` chyba trzeba dodać do dzieci tego `template`. https://eslint.vuejs.org/rules/no-v-for-template-key.html

Próbowałem i przy zachowaniu template daje to czas około 4s dla resetu filtra nazw przedmiotów. W porównaniu do indeksowanego tbody ~1.2s. Co ciekawe nieindeksowane tbody daje podobny czas ~1.5s.
Zastanawiam się, czy problemem nie jest tutaj to, że dwa tr składające się na jeden wspólny element nie są połączone w grupę np. poprzez tbody. Może vue prościej to optymalizować.

2022-04-25 17:44 UTC, lgpawel commented
Wprawdzie nadal nie działa to _lightning fast_, ale jest oczywiście zdecydowanie lepiej niż poprzednio. Jeśli chodzi o popsutą alternację kolorów, to ja bym zaakceptował hotfixa z dodaniem deklaracji trzeciego koloru (np. `rgba(0,0,0,0.1)`) dla wierszy z nazwami przedmiotów, a więc _pierwszych_ w każdym `<tbody>`.

Dobrze byłoby powoli zmierzać do zamknięcia tego PR, a optymalizację można moim zdaniem zostawić na przyszłość komuś innemu jako nowy issue. Proponuję, żeby zrobił Pan to, co napisałem w poprzednim akapicie i zmienił agregację liczby oczekujących z sumy na maksimum. Ale najważniejsze byłoby, żeby wreszcie rozwinąć opis PR o faktycznie względnie wyczerpujące objaśnienie wprowadzonych zmian. Tworzy Pan ok. 10 nowych plików, a w dwóch kolejnych wprowadza Pan daleko idące zmiany, w szczególności ze starego `zapisy/apps/statistics/templates/statistics/groups_list.html` nie zostaje prawie nic – tego nie można zostawić bez dodatkowych informacji, w tym jak te nowo stworzone pliki się do siebie nawzajem odwołują itd.

2022-04-30 17:10 UTC, lgpawel commented on zapisy/apps/statistics/templates/statistics/groups_list.html
> +    <p class="row justify-content-center">
Ten element nie jest chyba nigdzie zamykany.

2022-05-13 16:04 UTC, lgpawel approved these changes

2022-05-13 16:05 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +  <table class="table table-striped" id="darker-first-row">
Wprawdzie w generowanej stronie jest tylko jedna taka tabela, ale nawet sama nazwa sugeruje, że to raczej powinna być (kolejna) klasa, nie ID elementu.

2022-05-13 18:50 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/statistics_table.css
> +#darker-first-row.table-striped > tbody > tr:nth-child(1) {
Style powinny być w pliku `StatisticsList.vue`.
Chociaż być może bardziej elegancko byłoby ich nie mieć i użyć `<thead>` z odpowiednim akcentem: https://getbootstrap.com/docs/4.6/content/tables/#table-head-options.

2022-05-13 18:50 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +  created: function () {
Czemu to nie może być ustawione w `data`?

2022-05-13 18:50 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +      if (newSelected === undefined) {
Może lepiej nie dopuszczać pustej wartości `selected` i na starcie, domyślnie, mieć `npr`?

2022-05-13 18:50 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/filters/CheckFilter.vue
> +<script lang="ts">
Czy ten plik się różni od analogicznego w aplikacji `courses/timetable`?

2022-05-15 16:46 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/assets/components/filters/CheckFilter.vue
> +<script lang="ts">
Różni się wykorzystanymi filtrami.

2022-05-15 17:59 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/filters/CheckFilter.vue
> +<script lang="ts">
Nie rozumiem.
Diff jest minimalny.

2022-05-15 18:12 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/assets/components/filters/CheckFilter.vue
> +<script lang="ts">
Mam na myśli plik store/filters.ts. Są w nim różnice typów i nie jestem pewny, czy jest to poprawne. 
Zaimportowałem plik theses/assets/components/filters/CheckFilter.vue i wszystko działa, więc jeśli będzie w porządku to mogę to zmienić.

2022-05-16 08:39 UTC, jasiekmarc reviewed
Już chyba ostatnia seria komentarzy.

2022-05-16 08:39 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/filters/CheckFilter.vue
> +<script lang="ts">
Tak. Te filtry (`CheckFilter`, `TextFilter`) są już użyte w trzech miejscach i nie ma powodu, żeby ich po prostu nie użyć w czwartym (nawet jeśli to będzie wymagało zmiany dwóch linijek).

Tam chyba jest jakiś mały problem z typami, bo _CourseInfo_ w tamtej aplikacji jest czym innym niż _CourseInfo_ tutaj, ale jakimś prostym interfejsem się to powinno dać załatwić.

2022-05-16 09:10 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/views.py
> +            'alphabetical_sorting_index': i,
Tak. Przy tym zadaniu każda 0.1s ma znaczenie, bo już sam render znacznie obciąża przeglądarkę. Starałem się to zrobić czytelnie i nie powinno być to skomplikowane.

2022-05-16 10:22 UTC, jasiekmarc commented on zapisy/apps/statistics/views.py
> +            'alphabetical_sorting_index': i,
Jeśli faktycznie to muli, to znaczy, że jest jakiś głębszy problem „algorytmiczny”. Tych danych naprawdę nie jest tak dużo, a przeglądarki są teraz niesamowicie wydajne (aż za bardzo).

Obstawiałbym, że nie rozumiemy do końca, co Vuex wyczynia gdy zmieniają mu się parametry. Może sortuje 100 razy zamiast jeden. Warto by było to zdebugować (`console.log` naszym przyjacielem).

2022-05-16 10:24 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/views.py
> +            'alphabetical_sorting_index': i,
Tak jak pisałem wcześniej. Jest to problem z renderem. Wyłączenie sortowania i przepisywanie po prostu całej oryginalnej listy daje podobny rezultat.

2022-05-16 19:02 UTC, jasiekmarc commented on zapisy/apps/statistics/views.py
> +            'alphabetical_sorting_index': i,
Pochyliłem się nad tym i odkryłem, że da się ten problem naprawić. Można filtrować nie za pomocą przepisywania całej tablicy funkcją `filter`, tylko użyciem tagu `v-show` w template'cie.

2022-05-16 19:06 UTC, jasiekmarc requested changes

2022-05-16 19:06 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +              <option selected :value="undefined">-- Sortuj --</option>
To powinno zniknąć. W końcu `selected` jest typu _string_ i nie może przyjąć wartości _undefined_.

2022-05-16 19:06 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +    this.coursesList = this.courses;
Po załadowaniu strony przedmioty są nieposortowane.

2022-05-16 19:06 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +          <span
Między nimi musi być jakaś przerwa
![Screenshot from 2022-05-16 21-03-03](https://user-images.githubusercontent.com/5896456/168664249-29336194-cac4-4d7c-b2d1-88a61384d94f.png)

2022-05-16 19:11 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +          <span
Wydaje mi się, że komentuję tylko dodawany w tym PR kod.

2022-05-16 19:41 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +          <span
To pewnie technicznie prawda, ale w tym szczególnym przypadku to jest nowy kod realizujący stare zachowanie. Przy czym oczywiście zgadzam się, że jest ono nieidealne.

2022-05-16 19:46 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +    this.coursesList = this.courses;
Sortowanie zawarte w pliku view.py gwarantuje poprawną kolejność przedmiotów.

2022-05-18 19:27 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/views.py
> +            'alphabetical_sorting_index': i,
V-show załatwił sprawę. Nie ma potrzeby wtedy renderu elementów przez co teraz "odptaszanie" działa natychmiastowo.

2022-05-18 19:47 UTC, Damian-Dziedzic commented
Użyłem v-show tak jak polecił mi Pan @jasiekmarc dzięki czemu nie ma już problemu z powolnym resetem filtrów. Brak ponownych renderów po filtrowaniu pozwolił mi na przywrócenie wyglądu oryginalnej tabeli. Teraz kolorowanie pasów jest takie jak wcześniej.

2022-05-21 21:08 UTC, jasiekmarc requested changes
Już w zasadzie jesteśmy u celu.

Pozwoliłem sobie zasugerować jeszcze drobne uproszczenia.

2022-05-21 21:08 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +          break;
Te jedenaście linijek ma dokładnie ten sam kod, co linijki 42-52. Chyba można by to zdeduplikować. :-)

2022-05-21 21:08 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +        <tr v-show="visibleCourses[course.alphabetical_sorting_index]">
```suggestion
        <tr v-show="tester(course)">
```
Całe to `coursesList` i `visibleCourses` można wywalić.

2022-05-25 17:11 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +        <tr v-show="visibleCourses[course.alphabetical_sorting_index]">
Z jakiegoś powodu działając na samym courses bez coursesList nie ma reakcji na zmianę filtrów lub sortowanie.

2022-05-26 10:59 UTC, Damian-Dziedzic commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +        <tr v-show="visibleCourses[course.alphabetical_sorting_index]">
"Note that v-show doesn’t support the <template> element"
https://v2.vuejs.org/v2/guide/conditional.html

2022-05-26 11:02 UTC, jasiekmarc commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +        <tr v-show="visibleCourses[course.alphabetical_sorting_index]">
Już nie pamiętam, jak to testowałem. Chyba stworzyłem sobie osobny komponent na te parę wierszy w tabelce odpowiadających kursowi (ale wątpię, by to było konieczne).

W każdym razie na pewno to jakoś działało (i to szybko).

2022-05-28 19:01 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +    this.coursesList = this.courses;
I'm a bit late to the party, ale: u mnie teraz od razu po załadowaniu przedmioty owszem są posortowane względem nazwy… malejąco, i to przy adekwatnym dropdownie w pozycji "rosnąco". Jak przestawić tego dropdowna, to wszystko robi się spójne (choć, poniekąd oczywiście, nie można go przestawić w tę pozycję, w której już jest…). Oczywiście warto byłoby to poprawić.

2022-05-28 19:19 UTC, lgpawel commented on zapisy/apps/statistics/views.py
> +            course_name = group.course.name
Ja bym napisał to w formie _list comprehension_, żeby było widać, że w pętli nie ma żadnej skomplikowanej wewnętrznej logiki – ale może przy tak rozbudowanym wyrażeniu to już trochę przesada?

Niezależnie od tego do `course_name` robiłbym tylko jedno przypisanie, mianowicie z `courses[course_id][0].course.name` bo mamy chyba gwarancję, że wartości w `courses` są **niepustymi** listami.

2022-05-28 19:30 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +            label="Pokaż jedynie przedmioty, gdzie są niezapisani studenci"
```suggestion
            label="Pokaż jedynie przedmioty z oczekującymi studentami"
```

2022-05-28 19:40 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +        ["npm", "wg nazwy przedmiotu, malejąco"],
1. Zamieniłbym kolejność pierwszej i drugiej pary trybów tak, żeby domyślny był pierwszy w dropdownie.
2. "niezapisanych studentów" → "liczby oczekujących" (bez "studentów" dla oszczędności miejsca); brakuje mi też słowa "sortowanie" (być może jako label dropdowna) ale jakoś to przeżyję.
3. Wydaje mi się, że akronimy takie jak `npr` itd. pogarszają czytelność kodu dając mało istotną oszczędność na liczbie znaków. Proponuję `course_name_asc`, `waiting_students_desc` czy coś w tym rodzaju.

2022-05-28 19:42 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsFilter.vue
> +        <div class="col-lg-3">
To się trochę zmieni po uwzględnieniu innego mojego komentarza, ale w tej chwili ten element ma za mało miejsca – tu np. nawet nie widzę, w którą stronę sortowanie wybrałem.
![Screenshot_2022-05-28_21-41-21](https://user-images.githubusercontent.com/16328696/170840571-10cfedd9-6e62-4686-993a-d913f50c1af1.png)

2022-05-28 19:54 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +          </td>
Przed zmianą byłoby "8 + 2" i spacja przed nazwą grupy w _tooltipie_, przywróćmy to.
![image](https://user-images.githubusercontent.com/16328696/170840913-c84a465d-1c4b-4972-872d-ed49bd7e1b6f.png)

2022-05-30 17:18 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +              <span :title="'Miejsca gwarantowane dla grupy' + gs.name + '.'">
```suggestion
              <span :title="'Miejsca gwarantowane dla grupy ' + gs.name + '.'">
```

2022-05-30 17:19 UTC, lgpawel commented on zapisy/apps/statistics/assets/components/StatisticsList.vue
> +    this.coursesList = this.courses;
Nie wiem, czy zapomniałem kliknąć "unresolve" w tym wątku, czy co, ale niestety nadal nie mogę powiedzieć, że "u mnie działa". :disappointed:

2022-06-02 12:04 UTC, lgpawel approved these changes

2022-06-03 06:56 UTC, jasiekmarc approved these changes

2022-06-04 20:33 UTC, merged