Usunięcie None's z wybranych widoków
iiuni/projektzapisy pull request #1227
Opened 2022-03-29 16:10 UTC by bartoszputek

Po diagnozie problemu okazało się, że zgłoszony widok w issue korzysta z filtra [lookup](https://github.com/iiuni/projektzapisy/blob/64ebd48a27f1b910a0e5456f5577361671e493f5/zapisy/apps/common/templatetags/filters.py#L13) w przypadku braku znalezionej wartości w słowniku zwracana jest wartość `None`. 
Funkcja `lookup` działa zgodnie logiczną intuicją -> zwróć brak elementu zamiast np. 0, co mogło by prowadzić do potencjalnych problemów. Aby rozwiązać problem, został ~~stworzony nowy filtr `replaceNone`, który zastępuje wartość `None` na inną wartość (domyślnie 0)~~ użyty wbudowany filtr [default_if_none](https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#default-if-none).  Dodatkowo wszystkie widoki, które korzystały z filtra `lookup` zostały zrefaktoryzowane.

Closes: #1046

2022-03-29 16:11 UTC, bartoszputek commented
TODO:

- [ ]  Naprawienie problemów z lintowaniem
- [ ] Przejrzenie komentarza https://github.com/iiuni/projektzapisy/issues/1046#issuecomment-1082047730

2022-03-31 08:35 UTC, jasiekmarc commented on zapisy/apps/common/templatetags/filters.py
> +@register.filter(name="replaceNone")
To już chyba jest:
https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#default-if-none

2022-06-06 19:46 UTC, lgpawel requested changes
Pojawił się konflikt względem nowych zmian na `master-dev`, proszę o rozwiązanie go.

https://github.com/iiuni/projektzapisy/blob/cd2f288f81806ddbe506d25ae97640cecebade45/zapisy/apps/statistics/assets/components/StatisticsList.vue#L76

2022-06-23 18:32 UTC, lgpawel commented on zapisy/apps/grade/poll/templates/poll/results.html
>              {% endwith %}
A skoro identyfikator `x` pojawia się teraz już tylko raz, to czy jest nam w ogóle potrzebny?

2022-06-24 16:22 UTC, lgpawel commented
> Specjalnie znalazłem tę linijkę po to, żeby tam też użyć tego samego filtra (co jest być może nadmiarowe, ale nie zaszkodzi), analogicznie do przypadku, który został przeorany w ramach zmian w `master-dev`…

Po namyśle stwierdziłem, że może jednak trochę szkodzi: to jest sytuacja, w której nie chcemy, żeby wyświetlało się ani 0, ani _None_, ale w ogóle nic. Obecnie to działa, jak kiedyś przestanie, to jest może nieznacznie większa szansa, że ktoś to nam zgłosi, jak zobaczy _None_, a nie 0. A poza tym Nie Płacą Nam Od Linijki™ więc jednak bym wycofał tę zmianę; to samo rozumowanie tyczy się https://github.com/iiuni/projektzapisy/blob/9921f6633b2b3df26365ae72caf565c37815b706/zapisy/apps/enrollment/courses/templates/courses/course_parts/groups_section.html#L11 – tam parę linii wyżej mamy https://github.com/iiuni/projektzapisy/blob/9921f6633b2b3df26365ae72caf565c37815b706/zapisy/apps/enrollment/courses/templates/courses/course_parts/groups_section.html#L8 więc tak czy owak _None_ nie ma jak się pojawić.

Wszystko generalnie działa, ale proszę o uwzględnienie powyższych zmian, zwłaszcza wspomnianych wczoraj.

2022-06-25 21:27 UTC, lgpawel commented
Spodobał mi się ten filtr :smirk: Może w poniższych miejscach też by trochę uzwięźlił kod (on, albo `default`)?
https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/enrollment/courses/templates/courses/courses.html#L4-L8 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/offer/proposal/templates/proposal/offer.html#L9-L13 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/schedule/templates/schedule/classroom.html#L27 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/theses/templates/theses/thesis.html#L68-L72 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/theses/templates/theses/thesis.html#L77-L81 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/theses/templates/theses/thesis.html#L86-L90
https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/theses/templates/theses/thesis.html#L105-L109 https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/users/templates/users/employee_profile_contents.html#L37-L41

2022-06-25 23:15 UTC, bartoszputek commented
Dla linii:
https://github.com/iiuni/projektzapisy/blob/0f1b4014a30d652f7b60da12d736a02cd7525704/zapisy/apps/offer/proposal/templates/proposal/offer.html#L9-L13

Powyższy refactor nie jest tak prosty do użycia jak w pozostałych miejscach, z racji printowania atrybutu `name`, gdy sprawdzany jest czy obiekt `proposal` nie jest None.

2022-07-04 19:27 UTC, lgpawel commented
Dwie spośród wprowadzonych zmian, dla `courses.html` i `classroom.html`, psują – trzeba albo się wycofać, albo użyć innego filtra, być może `default`:
![image](https://user-images.githubusercontent.com/16328696/177208657-2fe5cac7-41b6-4915-97ef-01da2beac176.png)
![image](https://user-images.githubusercontent.com/16328696/177208599-c6803710-11ad-4ef3-9f39-169bff715a48.png)

A przy okazji znalazłem jeszcze jedno potencjalne `None` do ukrycia (`thesis.html`):
![image](https://user-images.githubusercontent.com/16328696/177207969-c96002e5-16aa-4e1d-a7b4-0bef1d43f65e.png)

Reszta jest OK.

2022-07-12 11:27 UTC, lgpawel approved these changes

2022-07-12 11:35 UTC, merged