Theses issue 1010
iiuni/projektzapisy pull request #1233
Opened 2022-04-04 16:14 UTC by Maria0123

Dodanie domyślnego ustawienia daty oddania pracy dyplomowej w formularzu zgłoszeniowym oraz w momencie akceptowania pracy

2022-04-05 09:40 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +    reserved_date = (datetime.date.today()+datetime.timedelta(days=730)).isoformat()
Czy ta data będzie przypisana do zmiennej w momencie wyświetlania formularza, czy też w momencie pierwszego załadowania tej klasy do pamięci (nie znam odpowiedzi na to pytanie)? To jest potencjalnie spora różnica: Robimy deploy, ktoś wyświetla formularz, przypisuje się zmienna, miesiąc później ktoś inny wyświetla formularz, ale zmienna ma już wartość sprzed miesiąca.

2022-04-05 09:42 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +    reserved_date = (datetime.date.today()+datetime.timedelta(days=730)).isoformat()
Dokumentacja odnosi się do tego pytania:
https://docs.djangoproject.com/en/4.0/ref/forms/fields/#:~:text=The%20callable%20will%20be%20evaluated%20only%20when%20the%20unbound%20form%20is%20displayed%2C%20not%20when%20it%20is%20defined

2022-04-14 16:13 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +    reserved_date = (datetime.date.today()+datetime.timedelta(days=730)).isoformat()
Intencja była chyba taka: w formularzu edycji tematu, w którym już jest ustawiona data rezerwacji, ma się wyświetlić wartość obecnie ustawiona w bazie; w formularzu dodawania nowego tematu (lub edycji takiego bez ustawionej daty rezerwacji) powinna się wyświetlić wartość związana z bieżącą datą. Jak rozumiem, to nie jest poprawnie zrealizowane, bo nie podajemy callabla, tylko jakąś wartość, która zostanie konkretnie wyliczona za pierwszym razem, kiedy ktoś obejrzy taki formularz.

Ale jak o tym teraz myślę, to to chyba był zły pomysł jeśli chodzi o UX: jeśli ktoś będzie chciał dodać temat bez rezerwowania go i dostanie wypełnione pole w formularzu, może zacząć się zastanawiać, czy nie powinien go opróżnić (zwłaszcza że raczej nie wie, że wewnętrzna logika funkcji `save` wynulluje tę wartość jeśli nie wybierze żadnych studentów do rezerwacji). Chyba powinno być tak:
- Formularz dla dodawania nowej / edytowania niezarezerwowanej pracy generowany jest bez wybranych studentów i pustą datą rezerwacji;
- Dla edytowania zarezerwowanej - oczywiście zgodnie z danymi z bazy;
- Jak zostaną zaznaczeni jacyś studenci, to data, jeśli jej wcześniej nie było, powinna się ustawić na za dwa lata, i może coś jeszcze powinno "mrygnąć" / pokazać dymek, że o, trzeba wybrać datę rezerwacji (albo zostawić taką, jaka się właśnie wypełniła)
- Jak zostaną odznaczeni wszyscy studenci, to pole z datą powinno się opróżnić (opcjonalnie)

2022-04-14 16:13 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +
Ten blok pewnie będzie mógł zostać niezależnie od dyskusji w drugim edytowanym fragmencie, ale – proszę mnie poprawić, jeśli się mylę – coś analogicznego powinno występować w kodzie metody `save` dla `ThesisForm`. (Czy udałoby się tu zachować się zgodnie z zasadą DRY? Ale oczywiście nie zamierzam się upierać.)

2022-05-13 17:17 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +            instance.reserved_unti.titll = None
Typo?

2022-05-13 19:45 UTC, jasiekmarc requested changes
Zostawiłem trochę komentarzy do tego skryptu w JS-ie, ale moim zdaniem on jest w ogóle zbędny.

Cały problem powinno się dać rozwiązać w Pythonie, dodając do metody `save` (albo `clean`) klasy `EditThesisForm` (i być może tej drugiej) ze trzy linijki kodu.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +  function showChange(reservedUntil) {
Funkcje powinny mieć opis oraz typy (lepiej pisać w TS niż JS).

Tę na przykład trzeba przeczytać, żeby zrozumieć, że bierze element HTML i nim mruga na czerwono.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +    }, 1500);
To się powinno swoją drogą dać załatwić jedną linijką CSS.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +    var reservedUntilLabel = $('label[for="id_reserved_until"]');
JQuery od paru lat próbowaliśmy wycofać. Ostatecznie miało odejść wraz z aktualizacją Bootstrapa do v5. Rekomendowałbym zatem, żeby nie używać go w nowym kodzie.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +      reservedUntil.value = reservedUntilDate;
Nie mam 100% pewności, czy w każdej przeglądarce i każdym języku datę do formularza wpisuje się w tym samym formacie. Pamiętam, że były kłopoty z takimi rzeczami.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +      reservedUntil.classList.add("requiredField");
To pole nie jest tak naprawdę _required_, prawda? Można wysłać formularz bez wypełniania go.

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +  var studentsSelect = document.getElementById("id_students");
To jest id nadane przez Django?

2022-05-13 19:45 UTC, jasiekmarc commented on zapisy/apps/theses/assets/store/theses-date.js
> +  if (Boolean(reservedUntil.value) != requiredDate) {
A jak wywalimy studentów to chyba nie powinniśmy oznaczać tego pola od daty jako _required_?

2022-05-13 20:06 UTC, lgpawel commented on zapisy/apps/theses/assets/store/theses-date.js
> +      reservedUntil.value = reservedUntilDate;
To, w jakim formacie się _wpisuje_ to na pewno zależy od locale przeglądarki. Chyba nawet próbowałem o tym zgłaszać issue (a przynajmniej marudzić mailem) jakieś lata temu, po czym @jasiekmarc wytłumaczył mi, że to _my locale is bad and I should feel bad_. Jak potem przeglądarka taką datę wysyła, to ja nie wiem, ale zgaduję że tak, jak ją widzi użytkownik, czyli patrz wyżej.

2022-05-25 15:12 UTC, lgpawel commented on zapisy/apps/theses/assets/store/theses-date.js
> +  var studentsSelect = document.getElementById("id_students");
Zdaje się że tak, tj. pole jest deklarowane jako https://github.com/iiuni/projektzapisy/blob/5e21f68f0d30f6444461c466e1d6fd919f9719c1/zapisy/apps/theses/forms.py#L44-L48 a potem już tylko pakowane do layoutu.

2022-05-30 19:25 UTC, lgpawel commented on zapisy/apps/theses/assets/store/theses-date.js
> +      reservedUntil.value = reservedUntilDate;
Jak właśnie skomentowałem w #1264, wydaje się jednak, że "pod pokrywką" własność `value` pola `<input type="date">` jest normalizowana do postaci ISO(-podobnej), więc tak też musi wyglądać w żądaniu powstającym po odesłaniu formularza; to, jak to _widzi_ i _wpisuje_ użytkownik adekwatnie do swojego _locale_, jest niezależne.

Jak również właśnie skomentowałem w #1264, przyjemniej byłoby operować na datach jak na datach, a nie jak na napisach.

2022-06-21 09:51 UTC, jasiekmarc requested changes
Bardzo dobrze!

Tak z grubsza powinno wyglądać rozwiązanie zadanego problemu.
I fajnie, że jest test.

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +                                     uzupełnij również datę rezerwacji.",
W Pythonie jest taki fajny trick na łączenie stringów.
```suggestion
    reserved_until = forms.DateField(help_text="Jeżeli przypiszesz do pracy studentów, "
                                     "uzupełnij również datę rezerwacji.",
```

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +            raise forms.ValidationError("Nie przypisano studentów do pracy. Usuń datę rezerwacji")
Zazwyczaj trzymaliśmy się umowy, że stringi „dla człowieka” są otoczone `"`, a te „dla komputera” `'`.

```suggestion
        if 'students' in self.data and self.cleaned_data['reserved_until'] is None:
            raise forms.ValidationError("Do pracy przypisano studenta. Uzupełnij datę rezerwacji")
        if 'students' not in self.data and self.cleaned_data['reserved_until'] is not None:
            raise forms.ValidationError("Nie przypisano studentów do pracy. Usuń datę rezerwacji")
```

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +    </script>
Byłbym za przeniesieniem tego do osobnego pliku `.ts` i dołączeniem jako _bundle_. Wtedy dostajemy w prezencie type-check i linter.

Przy okazji warto pokonać pokusy i zrezygnować z niepotrzebnego użycia JQuery.

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +            var confirm_msg = 'Zapisanie zmian spowoduje ponowne przesłanie pracy do komisji.\n' +
To w sumie pytanie do @lgpawel:
Oczami wyobraźni widzę, jak jakiś pracownik wścieka się, że system każe mu potwierdzać zmiany („traktują mnie jak idiotę”), a sekundę później i tak wraca do formularza, żeby coś poprawić. No i w związku z tym, czy takie potwierdzanie w ogóle ma sens?

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/tests/test_status.py
> +                     'reserved_until': timezone.now(),
Nie wiem, czy to ma zastosowanie tutaj, ale parę razy do testów z udziałem czasu przydał nam się taki trick:
https://github.com/iiuni/projektzapisy/blob/2b5acedb394571ce5cbb404edb41c60aa2bad0c1/zapisy/apps/offer/vote/tests/test_forms.py#L79

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/tests/test_status.py
> +def test_reservation_date_valid(self):
Ten test jest poza klasą (wcięcia).

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +        self.max_number_of_students = self.instance.max_number_of_students
To naprawdę tak trzeba pole po polu kopiować?

A `reserved_until` tu nie powinno być?

2022-06-21 09:51 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +    reserved_until = forms.DateField(help_text="Jeżeli przypiszesz do pracy studentów,\
@lgpawel: Czy nie powinno być jakiegoś ograniczenia na czas rezerwacji?
Czy można zarezerwować temat na 20 lat?

2022-06-21 09:54 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +    reserved_until = forms.DateField(help_text="Jeżeli przypiszesz do pracy studentów,\
To jest oczywiście dobre pytanie, ale decyzja nie należy do mnie i w tej chwili nie czuję ciśnienia, żeby to rozstrzygać. Na ten moment wystarczy, że zapewnimy, że ten wybór daty w 2042 będzie brał się z aktywnego działania użytkownika.

2022-06-21 14:30 UTC, adiwili commented on zapisy/apps/theses/forms.py
> +        self.max_number_of_students = self.instance.max_number_of_students
@lgpawel Czy lepiej byłoby skopiować całą instancję?

2022-06-24 18:37 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +            raise forms.ValidationError("Nie przypisano studentów do pracy. Usuń datę rezerwacji")
Ten wątek nie jest _resolved_, tj. zaproponowana zmiana realizująca ww. konwencję nie zostaje wdrożona.

2022-06-24 18:56 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        self.max_number_of_students = self.instance.max_number_of_students
Chyba wszystko jedno, modulo fakt że może faktycznie milej by się to czytało. Oczywiście grunt, żeby sprawdzać tylko istotne pola (tj. wszystkie poza `reserved_until` i `students`) tam, gdzie "decydujemy" o cofnięciu pracy pod głosowanie. Ale i tu i tam **brakuje pola `description`**!

2022-06-25 22:18 UTC, lgpawel commented
Jak już wspominałem gdzie indziej, mam pozwolenie od władz, żeby usunąć z frontendu specjalny wygląd formularzy dla użytkownik z uprawnieniami admina SZ (bo te osoby i tak mają możliwości edycji przez panel Django). Załatwmy to tutaj, bo dzięki temu jest mniej przypadkologii w obsłudze obecnie implementowanej logiki.

Trzeba wyszukać odwołania do własności `user.is_staff` w aplikacji `theses`.
- W `models.py` jest jedno, którego jeszcze nie całkiem rozumiem i również z tego powodu póki co nie ruszamy go.
- W `views.py` jest ich kilka, każde w jakiejś alternatywie ze sprawdzeniem innych wielkości boolowskich, i tu wystarczy je usunąć (na moje oko ten kod prosi się zresztą o refaktor ze względu na powtarzające się fragmenty tych sprawdzeń, ale w tę króliczą norę nie będziemy teraz brnąć).
- W `forms.py` usuwamy specjalne zachowania dla użytkownika z uprawnieniami admina w:
  - logice zmian własności `status` pracy dyplomowej (w szczególności nie będzie chyba potrzebne używanie własności `self.is_staff` obiektów klasy `ThesisFormBase`),
  - widocznych polach formularza oraz jego _layoucie_,
  - dostępnych wyborach w polu `advisor`, tj. tak, jak każdy inny, ma tam mieć do wyboru tylko siebie (oczywiście można dyskutować czy to pole jest w ogóle potrzebne, ale dla wizualnego _feedbacku_ nie zaszkodzi; inna rzecz że już teraz powinno być nieaktywne i nawet jest nadawana własność HTML `readonly`, tylko że, o ile dobrze rozumiem, powinno to być `disabled` – to też naprawmy).

Zamiast tego wszystkiego będzie należało dla tych użytkowników dodać w `templates/theses/thesis.html` przycisk "Edytuj w panelu administracyjnym" obok ewentualnego zwykłego przycisku "Edytuj".

(@jasiekmarc na wszelki wypadek zapytam: czy ja tu nie proponuję czegoś zbyt ryzykownego?)

2022-06-27 11:01 UTC, jasiekmarc commented
> (@jasiekmarc na wszelki wypadek zapytam: czy ja tu nie proponuję czegoś zbyt ryzykownego?)

Nic **ryzykownego** tu nie widzę. A to ma być w tym samym PR?
(Oczywiście, usuwając jakiś kod dobrze jest z grubsza rozumieć, o co w nim chodzi 😄.)

2022-06-27 19:48 UTC, lgpawel commented
> A to ma być w tym samym PR?
No oczywiście mogłoby mieć swój, tak. I to wydają mi się niezbyt skomplikowane zmiany, więc może proponowałbym założyć brancza tylko na nie z osobnym PR, który szybko zmerdżuję i będzie można go zmerdżować tutaj.

2022-07-05 14:54 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +            instance.status = ThesisStatus.ACCEPTED.value
`"students"` → `'students'`

2022-07-05 16:08 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +            instance.status = ThesisStatus.BEING_EVALUATED.value
Co ciekawe, tę gałąź warto usunąć. Wejście do niej oznacza, że nie weszło się do poprzedniej, a więc, że nie zmieniło się w pracy nic "ważnego", interesującego komisję, i dającego powód do tego, by głosować nad pracą inaczej niż dotychczas; praca dalej jest w stanie "do poprawek".

2022-07-05 17:11 UTC, lgpawel commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +            var confirm_msg = 'Zapisanie zmian spowoduje ponowne przesłanie pracy do komisji.\n' +
Chyba nie rozumiem, o jakim scenariuszu mówimy, ale na wszelki wypadek zauważę, że jeśli użytkownik potwierdzi "poważne" zmiany, to poskutkują one resetem statusu pracy do `BEING_EVALUATED`, w którym kolejne edycje "sekundę później" nie będą już wymagały potwierdzenia.

2022-07-05 17:27 UTC, lgpawel commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +            var description = document.querySelector('textarea[name="description"]').value
Te zmienne nie powinny być inicjowane na podstawie stanu formularza, tylko na podstawie tego, czym go oryginalnie Django wypełniło, a oto scenariusz, w którym pojawia się różnica:

- ładuję formularz edycji, edytuję np. opis oraz datę rezerwacji (ale nie przypisanych studentów), klikam "Zapisz"
- dostaję dymek z ostrzeżeniem, że zmieniłem opis, potwierdzam
- wracam do formularza edycji, bo nie przypisałem studentów; pole "opis" jest wypełnione tak, jak je zmieniłem w poprzednim kroku (†)
- przypisuję studentów
- stwierdzam, że jednak tego opisu może bym nie chciał jednak zmieniać, ale
- klikam "Zapisz" i formularz zostaje odesłany bez ostrzeżenia, bo porównanie jest względem stanu (†) formularza, a nie oryginalnego
- brak profitu

Pewnie należałoby się jakoś dobrać do zawartości pola `origin_instance`, możliwe, że przyda tu się filtr `json_script`.

2022-07-05 17:29 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        self.fields['status'].required = False
Teraz to pole nie pojawia się w żadnym scenariuszu, więc warto przyjrzeć się odwołaniom do niego i zobaczyć, które są potrzebne.

2022-07-05 17:31 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        row_1 = Row(
Teraz ta zmienna jest tylko raz jednoznacznie inicjowana i raz używana, więc trochę niepotrzebna; podobnie `special_row` w siostrzanej klasie.

2022-07-05 17:35 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        self.fields['advisor'].widget.attrs['readonly'] = True
Douczyłem się z HTMLa i okazuje się, że elementy z atrybutem `disabled` są pomijane przy odsyłaniu formularzy, więc to, o czym wcześniej mówiłem, więcej psuje niż naprawia. Natomiast nie zmienia to faktu, że atrybut `readonly` nie dotyczy elementu `select`, więc można go usunąć, zaś pożądany efekt daje wyrzucenie "opcji" "--------" z tego dropdowna za pomocą argumentu `empty_label=None` w deklaracji pola `advisor`.

2022-07-05 17:59 UTC, lgpawel commented
> Trzeba wyszukać odwołania do własności `user.is_staff` w aplikacji `theses`.
> 
>     * W `models.py` jest jedno, którego jeszcze nie całkiem rozumiem i również z tego powodu póki co nie ruszamy go.

Ogarnąłem to: też to trzeba usunąć, w przeciwnym wypadku posypią się `PermissionDenied` – użytkownicy z uprawnieniami będą widzieć na stronie wszystkie prace, ale szczegółów niektórych z nich już im nie będziemy wyświetlać po ostatnich zmianach.

2022-07-07 11:08 UTC, Maria0123 commented on zapisy/apps/theses/forms.py
> +        self.fields['status'].required = False
Przyjrzałam się odwołaniom i nie zauważyłam niepotrzebnych.

2022-07-07 19:51 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        self.fields['status'].required = False
A mi się wydaje, że jak usunąć tę linię, drugą równobrzmiącą z siostrzanej metody oraz https://github.com/iiuni/projektzapisy/blob/736614bab8328957495fae3d70c50d7669dd480e/zapisy/apps/theses/forms.py#L52 to dalej wszystko działa. W formularzu nie ma już tego pola, co oczywiście nie wyklucza się z tym, że w samym _modelu_ (i w szczególności obiekcie `instance`) analogiczny atrybut dalej jest i rządzi się swoją wewnętrzną logiką.

2022-07-07 19:53 UTC, lgpawel commented on zapisy/apps/theses/forms.py
>          self.status = self.instance.status
Może drobnostka, ale: skoro kopiujemy już całe `instance`, to nie trzeba osobno zachowywać własności `status` – w metodzie `save` ta sama wartość będzie dostępna w obiekcie `origin_instance`. (A skoro już tu komentuję, to trochę zgrzyta mi tu słowo _origin_ – wolałbym może po prostu _old_.)

2022-07-07 20:22 UTC, lgpawel commented
Właściwie w obecnej logice to rozróżnienie
https://github.com/iiuni/projektzapisy/blob/736614bab8328957495fae3d70c50d7669dd480e/zapisy/apps/theses/forms.py#L133-L138
trochę straciło rację bytu (i rozjechało względem sytuacji, w których faktycznie praca będzie wracać do komisji), zresztą różnica w napisie na przycisku jest dość subtelnym i mało czytelnym szczegółem w UI. Przycisk może więc zawsze mieć napis "Zapisz" i być dodawany bezpośrednio w deklaracji `self.helper.layout` w konstruktorze nadklasy. (Po uwzględnieniu tej i innych uwag konstruktor `ThesisForm` nie będzie w ogóle wymagał przeciążania.)

2022-07-09 06:21 UTC, Maria0123 commented on zapisy/apps/theses/forms.py
>          super(ThesisForm, self).__init__(user, *args, **kwargs)
Nie, usunęłam ją

2022-07-09 20:29 UTC, lgpawel commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +    </script>
Jeśli teraz `old_instance` jest już zwyczajnym Pythonowym słownikiem, który w dodatku zawiera tylko potrzebne klucze (prawie – `advisor` jest do wywalenia z argumentu `fields` wywołania `model_to_dict`), to musimy dalej to robić tak rozwlekle? Nie wystarczy coś w stylu `{{ old_instance|json_script:"old_instance" }}`?

2022-07-09 20:56 UTC, Maria0123 commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +    </script>
wystarczy - usunęłam advisor i skróciłam ten fragment

2022-07-11 16:58 UTC, lgpawel commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +    </script>
```suggestion
```

2022-07-12 09:44 UTC, jasiekmarc commented on zapisy/apps/theses/templates/theses/thesis_form.html
> +            var confirm_msg = 'Zapisanie zmian spowoduje ponowne przesłanie pracy do komisji.\n' +
Rozumiem. Nie zrozumiałem, że to się dzieje tylko gdy praca zmienia status z zatwierdzonej z powrotem na ewaluowaną.

2022-07-12 10:06 UTC, jasiekmarc commented on zapisy/apps/theses/views.py
> +    confirm_changes = \
Te `\` na końcu linii są do uniknięcia. One nie poprawiają czytelności.

[Dobrze skonfigurowany YAPF](https://github.com/iiuni/projektzapisy/wiki/Wskaz%C3%B3wki%3A-Konfiguracja-Edytora#ustawienia-edytora) potrafi złamać linię tam, gdzie trzeba.

2022-07-12 10:59 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        if old_instance.title != instance.title or \
_Counterpoint_: linie takie jak https://github.com/iiuni/projektzapisy/blob/e26317e9d4d26ef47f87cb48be62b9111c668501/zapisy/apps/theses/views.py#L159-L160 wcale nie sprawiają na mnie lepszego wrażenia niż gdyby było tu jawne złamanie wtyłciachem np. po pierwszym `or`.

2022-07-12 11:30 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +        if old_instance.title != instance.title or \
To chyba _counterpoint_ do jakiegoś innego komentarza? 😛

2022-07-12 13:11 UTC, jasiekmarc commented on zapisy/apps/theses/forms.py
> +        if old_instance.title != instance.title or \
Faktycznie. Wydaje się, że to się da naprawić zmieniając `ChoiceField` na [`TypedChoiceField`](https://docs.djangoproject.com/en/4.0/ref/forms/fields/#typedchoicefield) ([źródło](https://code.djangoproject.com/ticket/22354#comment:1))

2022-07-12 13:19 UTC, lgpawel commented
Powoli zbliżamy się do finiszu. Widziałbym jeszcze następujące nietrywialne zmiany:

- Żeby użytkownik nie był zaskoczony koniecznością potwierdzania zmian, wyświeliłbym informację o niej bezpośrednio na stronie. Na przykład: bezpośrednio pod nagłówkiem "Edycja pracy dyplomowej" wstawić blok (ostylowany klasami `alert alert-warning`) z tekstem "Temat został już zaakceptowany przez komisję. Wprowadzenie zmian innych niż dotyczące daty rezerwacji i przypisanych studentów spowoduje przesłanie go z powrotem do decyzji komisji." W prawej części bloku mógłby pojawić się przycisk z napisem "Zresetuj pola formularza wymagające zgody komisji", który działałby na podstawie obiektu `old_instance`.
- Ostrzeżenie przy wysyłaniu formularza powinno zostać (ktoś może nieświadomie coś nacisnąć), ale powinno wymieniać wszystkie zmienione "newralgiczne" pola, a nie tylko pierwsze, jakie znajdzie. Natomiast reszta treści może być bardziej lapidarna ze względu na obecność ww. alertu. Przy okazji: może warto byłoby na potrzeby tego sprawdzenia sklecić obiekt również z **nowymi** wartościami z formularza, a potem sprawdzenie (i generowanie komunikatu) robić w jakiejś pętli, zamiast w pięciu `if`ach.

Dla ustalenia uwagi jeszcze _checklista_ ważnych poprawek, o których była mowa, ale jeszcze nie są wdrożone:
- [ ] podpinanie akcji pod przycisk przez `eventListener`, a nie jQuery
- [ ] usunięcie specjalnego traktowania użytkowników z uprawnieniami administratora z `models.py`
- [ ] rozstrzygnięcie, czy wykrywanie istotnych zmian w `forms.py` da się zrobić zwięźle(j), np. za pomocą `changed_data`

2022-07-12 13:21 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        if old_instance.title != instance.title or \
Jak to poskutkuje, to trzeba będzie wygenerować migrację, prawda?

2022-07-12 19:17 UTC, lgpawel commented on zapisy/apps/theses/forms.py
> +        self.old_instance = copy(self.instance)
Ta głęboka kopia teraz znowu przestała nam być potrzebna, wystarczy zachować samo pole `status`.

2022-07-12 19:20 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +        changed_field_list = changed_field_list.slice(0, -2);
`[str1, str2, str3].join(', ');`

2022-07-12 19:48 UTC, adiwili commented on zapisy/apps/theses/assets/theses-change.js
> +  };
Dla większości można wyszukać przypisane labele i faktycznie z nich skorzystać (usuwając gwiazdki, w części z nich). Problem jest z description. Nie pobieramy jego zawartości z pola o id "id_description".
Czy warto rezgnować ze struktury na rzecz dodatkowej ifologii?

2022-07-12 19:54 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +  };
Może i nie ma takiego pola, ale wciąż jest do niego `label` z odpowiednim atrybutem `for`, tj. taki element: `<label for="id_description" class="">Opis</label>` – więc może jednak da się bez ifologii? A jak się nie da to nie, już niech będzie redundancja deklarowanych napisów.

2022-07-12 21:13 UTC, jasiekmarc reviewed
Zostawiłem jeszcze mały wniosek racjonalizatorski do skryptu js. Generalnie przyjemnie się teraz czyta ten kod. Wszystko jest na swoim miejscu, wiadomo co-po co.

Metody `clean` i `save` się zrobiły takimi wzorcowymi funkcjami w Pythonie. Można było w życiu nie widzieć żadnego Pythona, a od razu widać, co robi ten kod i że nie może być inaczej napisany.

2022-07-12 21:26 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
O ile nie wątpię, że pewne rzeczy da się zrobić piękniej, to to, co opisałeś, miałoby (chyba?) niepożądany efekt w jednym (choć może nietypowym) scenariuszu, o którym już gdzieś wyżej pisałem: https://github.com/iiuni/projektzapisy/pull/1233#discussion_r914032671

2022-07-12 21:28 UTC, jasiekmarc commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
Gdy wysyłasz formularz, to strona (a wraz z nią js) się przeładowuje.

2022-07-12 21:31 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
No tak, i jako odpowiednik `old_instance` powstanie obiekt ze zmianami z pierwszego wysłania formularza. A my byśmy chcieli mieć obiekt w stanie takim, jak to, co póki co jest w bazie.

2022-07-12 21:34 UTC, jasiekmarc commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
Przepraszam, ale chyba nie rozumiem drugiego kroku scenariusza w takim razie.
„Potwierdzam”, to znaczy, że klikasz, że ma dokonać zmian (wysłać formularz)?

2022-07-12 21:36 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
Tak (w przeciwnym przypadku nic by się nie przeładowało), po czym backend wrzuci mnie z powrotem do formularza, bo zrobiłem niekonsystentną zmianę (przypisani studenci bez daty lub na odwrót).

2022-07-12 21:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
Ach, chyba rozumiem.
On wtedy w `old_instance` będzie miał stan z bazy, a w formularzu wsadzi ten stan, który dostał POST-em (ale go nie scommitował).
Dobrze rozumiem?

2022-07-12 21:43 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
Tak – i dosyć nam na dostępie do tego stanu z bazy zależy, żeby móc porównywać się zawsze do niego.

2022-07-12 21:46 UTC, jasiekmarc commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
No to się wycofuję z clou mojego komentarza (w życiu bym tak „na sucho” nie wpadł na taki scenariusz).

Natomiast w kwestii czysto koderskiej, być może warto faktycznie użyć `FormData`, żeby nie dłubać tak w tych polach formularza.

2022-07-12 21:47 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +      }
Pod każdym z tych `if`ów jest niby jedna instrukcja, ale są one jednak dość skomplikowane, a między sobą różnią się jednym znakiem. Proponuję zadeklarować dodatkową zmienną z napisem zależnym od stosownej liczby gramatycznej, a potem użyć jej w **jedynym** `return` (oczywiście pod `if (changedFields.length > 0)`).

2022-07-12 21:49 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    document.getElementById("old_instance").textContent
No przyznaję, że to zdecydowanie niedominujący scenariusz, ale nasunął mi się przy testowaniu (i tym sposobem widać, że coś przy tym robiłem! :nerd_face:), więc można go już stosownie obsłużyć.

2022-07-13 12:45 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +  };
Właściwie to tej struktury też nie potrzebujemy. Odwołujemy się do niej na dwa sposoby (po dwa razy): albo samych kluczy jako listy ważnych pól (zgodnie z nazwą), ale dokładnie ten sam zestaw kluczy ma `old_instance`, albo do samych elementów formularza, które można też właściwie równie zwięźle i bez żadnej ifologii wyłuskać za pomocą `document.querySelector(``.confirm-submit [name=${fld}]``)` (oczywiście z pojedynczymi backtickami, nie ogarniam w Markdown) gdzie `fld` to nazwa klucza.

Można też pobawić się z obiektami klasy `FormData` zgodnie z sugestią @jasiekmarc ale mam wrażenie, że wartości dodanej nie będzie z tego wiele (zwłaszcza że dla funkcji resetującej stan ważnych pól to chyba się nie przyda).

Na marginesie: ten selektor (podobnie jak ten podpinający funkcję pod zdarzenie `submit`) byłby bezpieczniejszy, gdyby `confirm-submit` było identyfikatorem elementu, nie klasą…

2022-07-13 12:47 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +      });
To, że ja, pisząc jakieś szalone notatki na marginesach, używam nazw zmiennych jak popadnie, nie powinno obniżać standardu Państwa kodu. `fieldName` i `fld` odnoszą się do tych samych pojęć, więc różne identyfikatory tylko wprowadzają szum.

2022-07-13 12:49 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +    "Czy na pewno chcesz zapisać zmiany w pracy dyplomowej?";
Jeśli w ogóle potrzebujemy to gdzieś przypisywać, to powinno się to odbywać wewnątrz jedynej funkcji, jaka korzysta z tego identyfikatora.

2022-07-13 12:54 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +        }
Intencja tego fragmentu kodu jest kompletnie nieczytelna. Jeśli nie chcemy mieć rozwlekłej instrukcji `if-else` to możemy skorzystać z operatora rodem z C: `changedFields.length == 1 ? "pole" : "pola"`.

2022-07-13 13:35 UTC, lgpawel commented
Jest jeszcze jedna (prosta!) rzecz, która by się przydała (i jestem prawie pewien, że o niej mówiłem, ale może tylko w przelocie na zajęciach, czy coś): w zamian za brak wariantowości formularzy dla osób z uprawnieniami administratora, oprócz wprowadzonych przeze mnie zmian do `admin.py`, dobry byłby link na stronie (nie formularzu!) indywidualnej pracy prosto do edycji tej konkretnej pracy w adminpanelu.

Innymi słowy, obok https://github.com/iiuni/projektzapisy/blob/theses_issue_1010/zapisy/apps/theses/templates/theses/thesis.html#L36-L46 chcielibyśmy wstawić coś analogicznego do https://github.com/iiuni/projektzapisy/blob/theses_issue_1010/zapisy/apps/statistics/templates/statistics/groups_list.html#L61-L65 tylko prowadzącego do http://0.0.0.0:8000/fereol_admin/theses/thesis/IDPRACY/change/.

Tymczasem w `theses-change.js` przydałyby się jakieś zwięzłe komentarze (po angielsku!), co właściwie jest w `old_instance` i co tak pracowicie wylicza funkcja podpinana pod `submit`.

Kto wie, być może to już ostatnie potrzebne zmiany?

2022-07-14 19:12 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +      }
```suggestion
      for (const fieldName in old_instance) {
        document.querySelector(`.confirm-submit [name=${fieldName}]`).value = old_instance[fieldName];
      }
```

2022-07-14 19:13 UTC, lgpawel commented on zapisy/apps/theses/templates/theses/thesis.html
> +                        Admin
"Edytuj w panelu administracyjnym" byłoby może za długie, ale może
```suggestion
                        Administruj
```

2022-07-14 22:40 UTC, lgpawel approved these changes
Dla mnie OK (z dokładnością do dwóch sugestii sprzed paru godzin oraz komentarzy w `theses-change.js`). Proszę o uaktualnienie i uzupełnienie o nieco technicznych informacji opisu PR w pierwszym poście.

@jasiekmarc dałeś kiedyś _request changes_ – i jak? :grin:

2022-07-15 16:19 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +  // title, supporting_avisor, kind, max_number_of_students and description.
```suggestion
  // Object old_instance contains the original values of mutable parameters of the thesis
  // that are subject to approval by the committee:
  // title, supporting_advisor, kind, max_number_of_students and description.
```

2022-07-15 16:22 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +  // switches the thesis back to the BEING_EVALUATED state
```suggestion
  // This function identifies which of the parameters subject to approval
  // have been changed, and if any are found, the user is shown a
  // confirmation dialog listing their human-readable names.
```

2022-07-15 16:23 UTC, lgpawel commented on zapisy/apps/theses/assets/theses-change.js
> +  // made to accepted parameters.
```suggestion
  // The reset button allows the user to undo the changes
  // made to parameters subject to approval.
```

2022-07-15 18:14 UTC, jasiekmarc approved these changes

2022-07-15 20:01 UTC, merged