Naprawa błędów gdy pola formularza SpecialReservation są nieprawidłowe
iiuni/projektzapisy pull request #1252
Opened 2022-05-09 19:16 UTC by TheenivU

Okazuje się, że nawet gdy pola w formularzu są nieprawidłowe, to funkcja clean modelu nadal się wykonuje.

To oznacza, że w czasie jej wykonywania trzeba założyć że dowolne pole modelu może nie istnieć albo mieć wartość niepoprawnego typu.

W tym przypadku, postanowiłem że najłatwiej będzie założyć że one są poprawne w bloku try, i zatrzymać od propagacji błędy spowodowane przez jego złamanie.
To nie powinno doprowadzić do innych problemów, bo w przypadku takiego błędu, walidatory pól i tak zatrzymają formularz od przejścia poprawnie.

Closes: #1060

2022-05-11 15:53 UTC, TheenivU commented
Oryginalny problem powstał przez niepoprawne wartości pól, zamiast ich brak.
Oprócz tego, te pola są domyślnie ustawione jako wymagane.

Może czegoś nie sprawdziłem bo nie wiem, ale mój komentarz i te rozwiązanie wynika z następującego testu:

Scenariusz:
![Screenshot_20220511_174205](https://user-images.githubusercontent.com/86236789/167892511-c35d2ccf-143c-4cb6-a5ad-0b2802e20fb6.png)
Po save w master-dev:
![Screenshot_20220511_174548](https://user-images.githubusercontent.com/86236789/167892654-a136aac4-2143-42ff-b35c-cbf679c7f0ee.png)
Po save w tym branch:
![Screenshot_20220511_174714](https://user-images.githubusercontent.com/86236789/167892826-60c1a1b4-f262-4f60-a5bb-ba7982b317cd.png)

2022-05-12 08:38 UTC, jasiekmarc commented
Rozumiem. To jest bardzo dziwne, że Django nie wykonuje prostych sprawdzeń tych pól przed bardziej złożonymi.

To jeszcze zaproponuję mały eksperyment:
Czy jeśli przeniesiemy linijkę
```python
super(SpecialReservation, self).clean()
```
na początek metody `clean()`, to kolejność sprawdzania dalej będzie nieprawidłowa?

2022-05-12 08:47 UTC, TheenivU commented
Pomyślałem o tym w czasie poprawy i pamiętam że sprawdzałem. Niestety nie zmieniło to rezultatu.

2022-05-12 12:55 UTC, jasiekmarc commented
Dobra, już chyba rozumiem, gdzie ta kolejność jest zaburzona.

W [tej linijce](https://github.com/iiuni/projektzapisy/blob/eed4f433f872be4bf33fecd0a5f1354a22b47f1a/zapisy/apps/schedule/admin.py#L14) konstruktor modelu [wywołuje `full_clean`](https://github.com/django/django/blob/3a82b5f655446f0ca89e3b6a92b100aa458f348f/django/forms/forms.py#L197).

Ten konstruktor jakieś zdumiewające rzeczy wyprawia — sprawdza, czy w wygenerowanych błędach jest określony string.
To nie może być dobrze.

2022-05-17 14:28 UTC, TheenivU commented
W końcu sprawdizłem.
Niestety, wyłączenie całego if'a (przez zakomentowanie) jedynie zmienia traceback, i w tym nie wchodzimy do naszego kodu przed funkcją clean:
```
Environment:


Request Method: POST
Request URL: http://0.0.0.0:8000/fereol_admin/schedule/specialreservation/add/

Django Version: 3.1.14
Python Version: 3.8.10
Installed Applications:
('rest_framework',
 'rest_framework.authtoken',
 'test_without_migrations',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'apps.users',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mailer',
 'apps.enrollment.courses',
 'apps.enrollment.records',
 'apps.enrollment.timetable',
 'apps.statistics',
 'apps.news',
 'apps.offer.preferences',
 'apps.offer.proposal',
 'apps.offer.vote',
 'apps.offer.desiderata',
 'apps.offer.assignments',
 'apps.common',
 'apps.schedule',
 'apps.grade.poll',
 'apps.grade.ticket_create',
 'apps.schedulersync',
 'apps.theses',
 'apps.effects',
 'django_extensions',
 'django_filters',
 'bootstrap_pagination',
 'crispy_forms',
 'apps.notifications',
 'django_cas_ng',
 'django_rq',
 'webpack_loader',
 'pagedown.apps.PagedownConfig')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'rollbar.contrib.django.middleware.RollbarNotifierMiddleware']



Traceback (most recent call last):
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1573, in _changeform_view
    form_validated = form.is_valid()
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/forms/forms.py", line 376, in full_clean
    self._post_clean()
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/forms/models.py", line 405, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/vagrant/env3/lib/python3.8/site-packages/django/db/models/base.py", line 1216, in full_clean
    self.clean()
  File "/vagrant/zapisy/apps/schedule/models/specialreservation.py", line 144, in clean
    if self.end_time <= self.start_time:

Exception Type: TypeError at /fereol_admin/schedule/specialreservation/add/
Exception Value: '<=' not supported between instances of 'NoneType' and 'datetime.time'
```

2022-05-17 21:08 UTC, jasiekmarc commented
Odszczekuję wszystko co mówiłem.
https://github.com/django/django/blob/2cec020f5bc462954d902bdad1a5955852cecff6/django/db/models/base.py#L1468-L1469
Głupie to.

2022-05-17 21:10 UTC, jasiekmarc commented on zapisy/apps/schedule/models/specialreservation.py
> +        except Exception:
Tu jednak należałoby wyłapywać tylko takie wyjątki, jakich się spodziewamy.

2022-06-10 10:57 UTC, lgpawel commented on zapisy/apps/schedule/models/specialreservation.py
> +        except Exception:
W sumie jeśli chodzi o rozwiązanie *tego konkretnego* problemu, wystarczyłaby trochę oszczędniejsza poprawka: `try` obejmujące samego pierwszego `if`a z `except TypeError: pass`. Oczywiście byłoby idealnie, gdyby wnikliwie zastanowić się nad potencjalnymi innymi wyjątkami, które mogą polecieć w pozostałych instrukcjach obecnie pod `try`, ale
![](https://i.kym-cdn.com/photos/images/newsfeed/000/284/529/e65.gif)

2022-06-21 12:48 UTC, TheenivU commented
Zmieniłem łapany błąd na bardziej specyficzny TypeError, i to rozwiązanie nadal działa.
Ale ten blok nadal musi obejmować wszystkie trzy if-y, w razie gdyby pole sala było puste.

2022-06-23 17:08 UTC, lgpawel requested changes
Konkretne _issues_, które wywołały temat, faktycznie ta poprawka naprawia. Ale skoro już wspomina Pan o tym, co się będzie działo dla pustej sali, to (również z poprawką) mamy

- dla pustego semestru:
```
RelatedObjectDoesNotExist at /fereol_admin/schedule/specialreservation/add/
SpecialReservation has no semester.
```
- dla pustej sali:
```
RelatedObjectDoesNotExist at /fereol_admin/schedule/specialreservation/add/
SpecialReservation has no classroom.
```
- dla pustego dnia tygodnia:
```
ValueError at /fereol_admin/schedule/specialreservation/add/
'' is not in list.
```
Tak że żeby Zrobić To Dobrze™ (i zgodnie z ogólnie sformułowaną nazwą tego PR) trzeba jeszcze kilka rzeczy połapać i/lub po prostu wymusić w modelu jako niepuste (i wygenerować odpowiednią migrację).

Notabene jeśli dobrze rozumiem intencję stojącą za separacją metod `Model.clean_fields` i `Model.clean`, to sprawdzanie, czy sala jest przeznaczona do rezerwacji powinno być w tej pierwszej, której się obecnie nie przeciąża. (Sprawdzanie konfliktów już nie, bo odnosi się do kilku pól.)

Przy okazji proszę wycofać zmiany z `.gitignore`, one pewnie mają sens, ale są Nie Na Temat™.

2022-07-04 14:48 UTC, lgpawel commented
Coś połapaliśmy, ale czy dobrze?
- `ValueError` jest strasznie typowym wyjątkiem, trochę obawiam się łapania go w ciemno tak wysoko. W tym przypadku rzucany jest on w https://github.com/iiuni/projektzapisy/blob/0b896a5639c31f4c01668b7e58da9092a1d07674/zapisy/apps/enrollment/courses/models/term.py#L88-L90 Ta metoda wywoływana jest chyba tylko w jednym miejscu, więc relatywnie bezpiecznie można przy niej majstrować, np. żeby złapać `ValueError` z metody `index` już w niej. BTW wygląda na to, że jeśli tak zrobimy i w razie wyjątku zwrócimy `None`, to na ten poziom dolatuje… `TypeError` (z `validate_against_all_terms`).
- Łapiemy `ObjectDoesNotExist` choć to najwyraźniej nadklasa rzucanego `RelatedObjectDoesNotExist` i z jednej strony jak zawsze dobrze byłoby łapać wyjątki jak najostrożniej, ale z drugiej nie da się ukryć że ta specyficzna klasa jest zadeklarowana w dość chyba piekielny sposób w https://github.com/django/django/blob/d12d7c4c42814736c24731a6a300a79526fc2ef6/django/db/models/fields/related_descriptors.py#L105-L116 Chyba prosiłbym @jasiekmarc o opinię, jak z tego najlepiej wybrnąć, żeby nie oszaleć.

Przypominam jeszcze o sugestii, że sprawdzenie `self.classroom.can_reserve` powinno znaleźć się w metodzie `clean_fields` (obecnie nieprzeciążonej) oraz że przydatny byłby aktualny i kompletniejszy (uwzględniający znalezioną przyczynę problemu) opis zmian z całego PR.

2022-07-04 17:32 UTC, TheenivU commented
Wgram poprawkę do `ValueError` niedługo, a teraz wyjaśnię co się dzieje w tym PR.

Problem:
Okazuje się, że przynajmniej w wypadku panelu administratora, w czasie dodawania nowego wpisu, funkcja `clean()` modelu jest wykonywana nawet w przypadku, gdy walidacja pól wg. ich właściwości nie przeszła.
W konsekwencji, w czasie wykonywania metody te pola mogą być puste, zawierać dane o niewłaściwym formacie, odnosić się do nieistniejących rekordów w innych tabelach, itp. mimo że założenia modelu są inne.

Proponowane rozwiązane:
Użyć bloku `try` by wyłapać błędy wyrzucone przez te złamane założenia.
Aktualnie to są
- `TypeError` (rzucane gdy puste/niepoprawna zawartość pola)
- `ObjectDoesNotExist` (rzucane gdy rekord nie istnieje w powiązanej tabeli) (lepiej gdyby było `RelatedObjectDoesNotExist`, ale to jest dynamiczny typ zdefiniowany w `ForwardManyToOneDescriptor`, który dziedziczy wewnętrzną klasę modelu `DoesNotExist` (oraz `AttributeError`), która dziedziczy globalną klasę `ObjectDoesNotExist`)
- `ValueError` (rzucane przy konwersji dnia tygodnia w złym formacie kilka funkcji w dół)

2022-07-04 18:10 UTC, TheenivU commented
Zmieniłem funkcje `get_python_day_of_week` by zwracała `None` zamiast wyrzucać `ValueError`.
Dzięki temu niepoprawna wartość `dayOfWeek` jest łapana przez `TypeError`.

Niestety próba użycia `self.DoesNotExist` zamiast `ObjectDoesNotExist` nie zadziałała (wydaje mi się, że dwa `RelatedObjectDoesNotExist` dziedziczą `DoesNotExist` tych powiązanych modeli)

2022-07-04 21:37 UTC, lgpawel commented
> Zmieniłem funkcje `get_python_day_of_week` by zwracała `None` zamiast wyrzucać `ValueError`. Dzięki temu niepoprawna wartość `dayOfWeek` jest łapana przez `TypeError`.

Super, to może Pan od razu wyedytować opis PR z wcześniejszego posta.

> Niestety próba użycia `self.DoesNotExist` zamiast `ObjectDoesNotExist` nie zadziałała (wydaje mi się, że dwa `RelatedObjectDoesNotExist` dziedziczą `DoesNotExist` tych powiązanych modeli)

Ale próbował Pan literalnie `self.DoesNotExist` czy jednak konkretnie `Semester.DoesNotExist` i `Classroom.DoesNotExist`?

2022-07-04 21:45 UTC, TheenivU commented
Literalnie `self.DoesNotExist`/`SpecialReservation.DoesNotExist`
Spróbowałem właśnie instancje które pan zasugerował, i one zadziałały.

2022-08-01 19:56 UTC, merged