1223 replace bootstrap sortable
iiuni/projektzapisy pull request #1292
Opened 2022-06-08 17:36 UTC by doubleduck98

Nowy pakiet spełnia postawione wymagania w #1223 tj. działa poprawnie, jest zaciągany z npm i wykorzystuje zależności już obecne w projekcie. Jedyną wadą jest tylko to, że mniej elegancko rozwiązuje problem ikonek, więc zamiast zaciągać stylesheet z cdn'a, wprowadziłem go "ręcznie", tak żeby poprawnie wskazywał kierunek sortowania.

2022-06-10 11:42 UTC, lgpawel requested changes
Wygląda OK, ale wydaje mi się, że – w przeciwieństwie do stanu obecnego – tabele nie zostają posortowane od razu po załadowaniu i oczywiście warto byłoby to zachowanie pozostawić.

Proszę przy okazji sprawdzić, czy umielibyśmy w tym miejscu naprawić odwieczny problem lokalizacji sortowania – zarówno w wersji produkcyjnej, jak i z tą poprawką, mamy np. tak:
![image](https://user-images.githubusercontent.com/16328696/173057494-a50b9307-2aec-4278-83d5-861de054f704.png)

2022-06-10 11:42 UTC, lgpawel commented on zapisy/apps/offer/vote/assets/bootstrap-table.scss
> +}
Niezbyt podobają mi się te bloby; chciałbym, żeby ten sam efekt uzyskać bez nich. Dwa pomysły, być może niecelne: skorzystać z `fontawesome`, które i tak zaciągamy i gdzie nadające się ikonki pewnie są, i _zainspirować się_ CSSem z pakietu, z którym chcemy się pożegnać: https://github.com/drvic10k/bootstrap-sortable/blob/master/Contents/bootstrap-sortable.css

2022-06-23 18:35 UTC, lgpawel commented
Skoro już grzebiemy w tej stronie: obecna kolejność semestrów (letni, _unknown_, zimowy) jest zgodna z alfabetem, ale nie zdrowym rozsądkiem. Proszę zastąpić ją przez: zimowy, letni, _unknown_.

2022-07-08 18:33 UTC, lgpawel commented on zapisy/apps/offer/proposal/templatetags/proposal_status.py
> +    return sorted(proposals, key=lambda p: ordering[p.semester])
Nazwa tego pliku wiąże się tematycznie z filtrem dotychczas się w nim znajdującym, ten nowy (choć oczywiście dobrze rozwiązuje problem) pasuje tu jak pięść do nosa. Ja bym się nie krępował i zdefiniował to w nowym pliku (który umieściłbym gdzieś pod `/zapisy/apps/offer/vote`, nie `.../proposal`, żeby był bliżej jedynego w tym momencie użycia).

2022-07-16 18:26 UTC, lgpawel commented
Jeszcze jedna rzecz na marginesie, bo może to wystarczająco łatwe: czy możemy sprawić, żeby kolumny w we wszystkich trzech tabelach miały takie same szerokości? Można by zrobić jedną tabelę z "nagłówkowymi" wierszami o scalonych komórkach w środku, ale pytanie czy będziemy mogli zmusić `tablesorter` do sortowania tylko określonej części tabeli. Alternatywnie, biorąc pod uwagę bardzo określony rodzaj zawartości wszystkich kolumn poza pierwszą, można by im ograniczyć szerokość CSSem (ale oczywiście unikając zawijania tekstu w nagłówkach).

2022-07-19 18:27 UTC, lgpawel commented
Używając `width: max-content` mogę pozbyć się dwóch ręcznie wybranych procentów. Niestety pozostaje to ręcznie wybrane 5% dla ostatniej kolumny, które jest potrzebne przy `table-layout: fixed`, z kolei bez którego trzebaby coś deklarować dla pierwszej kolumny, a `width: 100%` psuje inne rzeczy…

2022-07-22 18:00 UTC, lgpawel commented
Wystarczyło zabrać `float: right` ikonkom sortowania dla innych kolumn niż pierwsza (i dodać `white-space: nowrap` komórkom nagłówkowym, ale to już wcześniej sprawdzałem).

2022-10-31 21:11 UTC, TWolczanski commented
Uznałem, że najlepszym sposobem na sprawienie, aby tabele miały tą samą szerokość kolumn, będzie połączenie ich w jedną. Niestety nie znalazłem żadnego pakietu, który sortowałby tylko określone części tabeli, więc sam zaimplementowałem sortowanie.

2022-11-12 16:24 UTC, TWolczanski commented
Okazuje się, że po ustawieniu szerokości pierwszej kolumny na 60% wszystkie kolumny mają prawie taką samą szerokość, jak w wersji produkcyjnej. W szczególności tekst w komórkach nagłówkowych drugiej i trzeciej kolumny zaczyna zawijać się przy tej samej szerokości ekranu.

Dodałem jeszcze breakpoint ukrywający ikonki na małym ekranie, chociaż nie jestem pewien, czy to dobre rozwiązanie.

2024-01-27 18:24 UTC, lgpawel commented on zapisy/apps/offer/vote/assets/sortable-table.js
> +  $(".table").tablesorter({
Być może ostatnie pytanie, jakie tu mi się nasuwa to to, czy możemy podpiąć te funkcjonalności pod tabele bez jawnego używania jQuery. Może nie, skoro... sam `tablesorter` jest w jQuery, ale chciałbym to potwierdzić.

2024-01-30 14:42 UTC, UniJanJan commented on zapisy/apps/offer/vote/assets/sortable-table.js
> +  $(".table").tablesorter({
Dokonałem pewnego riserczu w sieci i nie znalazłem sposobu na inicjację `tablesortera` w innej formie, niż w tej przedstawionej powyżej.

2024-02-03 20:41 UTC, lgpawel approved these changes

2024-02-07 20:16 UTC, lgpawel commented on zapisy/apps/offer/vote/assets/sortable-table.scss
> +      @media (max-width: 32rem) {
To jest fajne, ale powiązałbym to z jakimś standardowym breakpointem BS, nawet już jakimś szerszym zresztą.

2024-02-07 20:16 UTC, lgpawel commented on zapisy/apps/common/assets/main/icons-library.js
> +library.add(faTimes);
Nie przypominam sobie, żebym widział te ikonki w użyciu na wiadomej stronie, może można ich nie ładować?

2024-02-07 21:26 UTC, UniJanJan commented on zapisy/apps/common/assets/main/icons-library.js
> +library.add(faTimes);
W rzeczy samej, nigdzie w kodzie nie znalazłem wykorzystania tych ikon. Również po zlikwidowaniu powyższych linijek kodu nie dostrzegłem żadnych problemów.

2024-02-07 21:29 UTC, UniJanJan commented on zapisy/apps/offer/vote/assets/sortable-table.scss
> +      @media (max-width: 32rem) {
Ustawiłem nową cezurę na 768px.

2024-02-07 22:26 UTC, lgpawel commented on zapisy/apps/offer/vote/assets/sortable-table.scss
> +      @media (max-width: 768px) {
No, mało to semantyczne. Jeśli dobrze rozumiem, poniższe będzie miało de facto ten sam efekt, a nie hardkoduje wartości zmiennej w dodatkowym miejscu (tak, zapewne mamy ich już sporo, ale każdy moment jest dobry, żeby przestać – czy nie?)
```suggestion
      @include media-breakpoint-down(md) {
```

2024-02-08 11:05 UTC, UniJanJan commented on zapisy/apps/offer/vote/assets/sortable-table.scss
> +      @media (max-width: 768px) {
Ano, to jest znacznie lepszy zapis. Musiałem też dodać w tym pliku dodatkowe importy, aby móc tej formy użyć.

2024-02-08 21:26 UTC, merged