Refactoring of theses
iiuni/projektzapisy pull request #1307
Opened 2022-06-21 20:07 UTC by Damian-Dziedzic

2022-07-08 16:47 UTC, lgpawel requested changes
Jest:
![image](https://user-images.githubusercontent.com/16328696/178034815-043089be-ce13-4bfc-b9b9-6829460771cb.png)
Było:
![image](https://user-images.githubusercontent.com/16328696/178035571-ad6624b4-4ab4-423b-8fab-b6305c600f03.png)

2022-07-12 09:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -  // The list should be initialised to contain all the theses and then apply
https://www.lexico.com/definition/initialize#:~:text=(also%20British%20initialise)

2022-07-12 09:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
>      this.$store.subscribe((mutation, state) => {
Uwaga do linii 38-39:
Chyba dwa przypisania są niepotrzebne?

2022-07-12 09:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
>    visibleTheses: ThesisInfo[] = [];
Skoro nie filtrujemy, to ta nazwa chyba już nie jest adekwatna.

2022-07-12 09:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/sorters/SorterField.vue
> +          f: !this.order,
Jakiego typu jest `order`?

2022-07-12 09:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -      isEmpty: "isEmpty",
Czy to znika również ze `store`?

2022-07-15 16:58 UTC, Damian-Dziedzic commented on zapisy/apps/theses/assets/components/ThesesList.vue
>            break;
Tylko triggerem. Usunięcie linii 44. powoduje brak jakiejkolwiek reakcji na zmianę filtrowania.

2022-07-15 17:01 UTC, Damian-Dziedzic commented on zapisy/apps/theses/assets/components/sorters/SorterField.vue
> +          f: !this.order,
Liczbowego równego 1 lub 0 w "else".

2022-07-15 17:08 UTC, Damian-Dziedzic commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -      isEmpty: "isEmpty",
Nie widzę tej funkcji w store/sorting.ts.

2022-07-15 18:16 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/sorters/SorterField.vue
> +          f: !this.order,
Ten typ jest zapewne gdzieś zadeklarowany (jako int).
I dlatego właśnie nie można zrobić `!this.order`, bo `order` nie jest bool-em.

2022-07-15 18:30 UTC, jasiekmarc reviewed
Ten PR zawiera zbiór luźno powiązanych modyfikacji front-endu do aplikacji _theses_ (co nie jest niczym złym — porządkowanie na tym polega).

👍 Jestem za usunięciem `isEmpty`, które ewidentnie jest jakimś artefaktem wcześniejszych pomysłów.
👍 Jestem za przeniesieniem konstruktorów z `created()` do `data()`.
👎 Jestem przeciwko zmianie z `!order`. `order` nie jest boolem (to jest API javascriptowej funkcji `sort`, a nie nasz wybór) a liczb się nie neguje.
👎 Jestem przeciwko zmianie z `v-if` na `v-show`. Rozwiązywany jest tu problem, który nie istnieje (nie daje się nam we znaki), a generuje to problem z pustą listą, który rozwiązany jest nader nieelegancko.

2022-07-15 18:30 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -      isEmpty: "isEmpty",
Faktycznie. Ciekawe.

2022-07-15 19:02 UTC, lgpawel commented
Przychylam się do opinii @jasiekmarc, plus jeszcze moje 3 gr:

> :-1: Jestem przeciwko zmianie z `!order`. `order` nie jest boolem (to jest API javascriptowej funkcji `sort`, a nie nasz wybór) a liczb się nie neguje.

To, że kompilator, interpreter, czy nawet linter nie krzyczą na nas, nie znaczy jeszcze, że robimy coś dobrze. Używanie operacji zgodnych z typami może sprawiać, że kod będzie czytelniejszy (niedawny przykład z tego repozytorium: dłuższą chwilę mi zajęło zrozumienie, że `sum(lista_list, [])` w Pythonie to po prostu _flatten_ – bo takie to nieidiomatyczne, a wręcz niezgodne z tym, co zalecają w dokumentacji `sum` – i poprosiłem o zastąpienie kilku wystąpień takich wywołań czymś bardziej zrozumiałym). Gdyby zyskiem była szybkość działania albo np. jakaś niesamowita zwięzłość, to jeszcze, ale tu spieramy się dosłownie o cztery znaki.

> :-1: Jestem przeciwko zmianie z `v-if` na `v-show`. Rozwiązywany jest tu problem, który nie istnieje (nie daje się nam we znaki), a generuje to problem z pustą listą, który rozwiązany jest nader nieelegancko.

Jak zobaczyłem ten PR, to miałem nadzieję, że ta zmiana motywowana jest np. przyspieszeniem renderowania strony, ale niestety nic się zauważalnie nie zmieniło. A zysk w zwięzłości i elegancji zjadło sprawdzanie, czy trzeba wyświetlić _placeholder_, czy nie…

2022-07-15 19:04 UTC, lgpawel commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -  // The list should be initialised to contain all the theses and then apply
Skoro to już jest podniesione oraz spieramy się w tym PR o pojedyncze znaki, i ponieważ sprawa rozbija się o arbitralną odgórną decyzję, to jako stronnik _Oxford spelling_ proszę o wycofanie tej zmiany.

2022-07-15 19:15 UTC, lgpawel commented on zapisy/apps/theses/assets/components/ThesesList.vue
>            break;
Ponieważ to pytanie zdaje się wróci razem z _revertami_, o które prosimy, to: czy nie da się napisać tego bez powtórzeń kodu? W języku, z którego pochodzi (?) ta składnia, równoważne byłoby
```javascript
switch (mutation.type) {
  case "filters/registerFilter":
  case "sorting/changeSorting":
  // do stuff
}
```

2022-07-15 20:13 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/ThesesList.vue
> -  // The list should be initialised to contain all the theses and then apply
Mój komentarz dotyczył zmiany **s** na **z**.
Pan @Damian-Dziedzic postanowił zastosować opcję atomową i usunął cały komentarz.

2022-07-15 20:41 UTC, jasiekmarc approved these changes
Dziękuję za szybkie zmiany. Proszę również o zaktualizowanie opisu Pull-Requestu.

2022-07-15 20:41 UTC, jasiekmarc commented on zapisy/apps/theses/assets/components/sorters/SorterField.vue
> +          f: this.order == 0,
To mnie dalej nurtuje, dlaczego ktoś napisał `this.order + 1 == 1`. Przecież chyba każdy nasz student wie, że jeśli `x + 1 = 1`, to `x = 0`? Nie wykluczam, że to jakiś JS-owy trick ze słabą równością (generalnie równość w JS-ie sprawdza się `===`).

Proszę to zmienić na `===` i przetestować. I proszę napisać w komentarzu, że Pan skompilował, przetestował i że sortowanie w obie strony działa.

2022-07-15 20:54 UTC, Damian-Dziedzic commented on zapisy/apps/theses/assets/components/sorters/SorterField.vue
> +          f: this.order == 0,
Sprawdziłem i nic się nie zmieniło. Sprawdziłem nawet ze stroną z produkcji.

2022-07-16 11:26 UTC, lgpawel commented
Chętnie przywróciłbym jedną techniczną drobnostkę, która już się pojawiła, a potem została wycofana, a mianowicie zmianę używanego w iterowaniu po wyświetlanych pracach identyfikatora z `t` na `thesis` – czytało się to wtedy zdecydowanie lepiej.

2022-07-16 14:19 UTC, Damian-Dziedzic commented
> Chętnie przywróciłbym jedną techniczną drobnostkę, która już się pojawiła, a potem została wycofana, a mianowicie zmianę używanego w iterowaniu po wyświetlanych pracach identyfikatora z `t` na `thesis` – czytało się to wtedy zdecydowanie lepiej.

Przywróciłem tę zmianę.

2022-07-19 20:43 UTC, merged