1564 duzy obrazek
iiuni/projektzapisy pull request #1573
Opened 2023-10-23 10:30 UTC by mbaugustyn

Nowy post wiadomości ("aktualności")  jest "parsowany" funkcją "markdownify", a następnie umieszczany w div o Bootstrapowej klasie "my-3". Ten div my-3 jest umieszczany w głównym kontenerze na stronie aktualności.
Sam div my-3 zawiera wyrenderowany markdown nowego posta w którym znajduje się m.in. plaintekst czy obrazki.

W obecnej postaci duże obrazki nie mieszczą się w swoich kontenerach przez co wychodzą poza swój kontener jak widzimy na skrinie:
![image](https://github.com/iiuni/projektzapisy/assets/32998370/a022f26c-7e73-40f5-be75-0a9c62e59646)

Według dokumentacji Bootstrapa v5.0 żeby osiągnąć responsywny image trzeba nadać mu klasę "img-fluid".
https://getbootstrap.com/docs/5.0/content/images/

Według mnie takie rozwiązanie wymagałoby znacznego nakładu kodu, bo musielibyśmy "dostać się" do nowego dodawanego obrazka i nadać mu odpowiednią klasę.
Dlatego moim rozwiązaniem jest dać każdemu dziecku my-3, który jest obrazkiem właściwość max-width:100%. Czyli maksymalna szerokość będzie 100% szerokością rodzica, czyli to co dałaby klasa "img-fluid".

Rozwiązanie przetestowałem na różnych obrazkach, przeglądarkach i urządzeniach.

2023-10-24 10:56 UTC, lgpawel requested changes
Trzeba zrobić to inaczej niż wprowadzając do globalnego CSSa zmianę, która może mieć wpływ na inne miejsca na stronie, i o której niedługo wszyscy zapomną, po co była. Wersja minimum to przeniesienie tej deklaracji do jakiegoś CSSa (być może wręcz wewnętrznego) związanego z podstronami, których dotyczy zmiana.

Ale może da się zrobić coś ciekawszego – proszę na początek pokazać palcem, gdzie jest przetwarzany tekst ogłoszenia.

2023-10-26 11:03 UTC, mbaugustyn commented
Tekst w ogłoszeniu jest przetwarzany w pliu _render-markdown.ts_. A dokładniej w funkcji callback która renderuje markdown do htmla.
Kontener w którym ten html się znajduje ma klasę "markdown-rendered".

1. Więc usprawniając trochę moje oryginalne rozwiązanie - zamiast dodawać styl do ogólnej klasy "my-3", możnaby stylować ten kontener "markdown-rendered" - nadać wszystkich jego dzieciom co są obrazkami odpowiednie width.

2. Rozwiązanie ciekawsze polega na dodaniu klasy "img-fluid" wszystkim obrazkom wyrenderowanym w tym sposób, co teraz uczyniłem poprzez użycie querySelector, dodaje każdemu dziecku w kontenerze, które jest obrazkiem klasę "img-fluid..

2023-10-31 09:14 UTC, lgpawel commented
No cóż, mi się zdecydowanie bardziej podoba rozwiązanie nr 1 – przynajmniej w sytuacji, w której już mamy plik `markdown-rendered.scss`, to on wydaje się idealnym miejscem na dodanie deklaracji, o której mówimy. Wydaje mi się zresztą, że im mniej dynamicznych rozwiązań (tu: żonglowania klasami CSS przez kod JS) tym efekt jest czytelniejszy (nawet jeśli nie ciekawszy).

Przy okazji: problem został wprawdzie zgłoszony w kontekście strony z aktualnościami, ale udało się go (mało zaskakująco) zidentyfikować z _widgetem_ do przetwarzania znaczników Markdown, należałoby więc prześledzić występowanie błędu (i skuteczność poprawki) na wszystkich podstronach używających tego _widgetu_. Zapewne będzie to wymagać dodania dużego obrazka do jakiejś propozycji przedmiotu, tematu pracy dyplomowej etc.

2023-11-12 19:57 UTC, mbaugustyn commented
Zgodnie z sugestia wystylizowalem klase markdown-rendered dodajac obrazkom odpowiedni width.

Widget do przetwarzania markdowna pojawia sie przy dodawaniu nowych aktualnosci, dodawaniu propozycji nowego przedmiotu oraz w nowej pracy dyplomowej. Wiecej miejsc wystepywania widgetu nie znalazlem.
W kazdym wypadku wygenerowany markdown jest opakowany klasa "markdown-rendered", wiec moje rozwiazanie w kazdym wypadku bedzie prawidlowo stylizowac obrazki.


Przyklady:
-
![image](https://github.com/iiuni/projektzapisy/assets/32998370/69507748-e5e2-46a1-984b-9077b0cb6219)
-
![image](https://github.com/iiuni/projektzapisy/assets/32998370/503ff15f-b202-492c-9efa-c2a0afa7f416)
- 
![image](https://github.com/iiuni/projektzapisy/assets/32998370/b351b222-0494-4169-9b52-e54a0aeea78b)

2023-11-24 17:00 UTC, mbaugustyn commented
Udało sie!
Już wygląda czysto.

2023-11-27 20:39 UTC, lgpawel commented
Poprawka działa i jest zrealizowana w dobrym miejscu, ale proponuję jeszcze bardziej wykorzystać ekspresywność SCSS i zamiast kopiować i wklejać własności `.img-fluid` użyć odpowiedniej instrukcji do odziedziczenia ich.

2023-12-08 07:53 UTC, merged