#1448 - kolumny równej szerokości
iiuni/projektzapisy pull request #1581
Opened 2023-10-28 20:35 UTC by Wojtek130

dotychczas kolumny tabelek dotyczących poszczególnych przedmiotów miały różne szerokości w przypadku różnych przedmiotów, aktualnie poprawiłem to i teraz każda kolumna zajmuje po 50% przestrzeni

2023-11-13 22:19 UTC, lgpawel requested changes
Ta zmiana, wprowadzona w głównym CSSie projektu, może mieć konsekwencje (dla odmiany negatywne) w innych podstronach systemu. W dodatku efekt nie jest raczej tym pożądanym – prawa kolumna mimo wszystko zawiera potencjalnie więcej danych niż lewa (por. drugi _screenshot_ w oryginalnym opisie _issue_), w dodatku jest tą zdecydowanie bardziej interesującą.

Idealnie byłoby wymusić na CSSie, żeby dawał prawej kolumnie maksymalnie dużo miejsca, ale tak, by łamanie wierszy w lewej kolumnie działo się tylko w ostateczności (albo ew. w ogóle, tj. jeśli nieuniknione okazałoby się by zakazać tego łamania, to można tak zrobić).

2023-12-01 16:16 UTC, Wojtek130 commented
Tutaj zapushowałem dwie prozycje rozwiązania (dwa ostatnie commity). Pierwsza z nich jest (moim zdaniem) wizualnie ładniejsza, ale programistycznie dość naiwa, zahardkodowuje 30% szerokości dla pierwszej kolumny, z kolei druga jest bardziej zgodna z tym, co Pan napisał - możliwie dużo miejsca jest przydzielone drugiej kolumniej, jednakże łamanie wierszy  pierwszej kolumnie jest zakazane.

2024-02-06 16:53 UTC, lgpawel requested changes

2024-02-06 16:53 UTC, lgpawel commented on zapisy/apps/enrollment/courses/templates/courses/course_parts/course_head.html
> +    }
Teraz jest faktycznie dosyć sztywno, ale takie coś chyba zarówno robi, co trzeba, jak i jest bardziej elastyczne. Nie wiem, czy nie wiążą się z tym jakieś kruczki, czy nie warto dodać czegoś jeszcze...
```suggestion
    #table-info th {
        min-width: max-content; 
    }
```

2024-10-09 18:40 UTC, lgpawel commented
Może kiedyś to wyglądało na skuteczne rozwiązanie, ale teraz nie wydaje się niestety, żeby robiło coś godnego uwagi, tak że temat nadal jest aktualny.

2025-02-09 10:37 UTC, closed without merging