#1587 Osoby przypisane do tematu pracy dyplomowej powinny widzieć go jeszcze przed akceptacją
iiuni/projektzapisy pull request #1602
Opened 2023-11-28 10:39 UTC by Ph0enixKM

Użytkownik mógł zobaczyć swoją pracę dyplomową w zależności od statusu. Teraz może ją zobaczyć niezależnie od statusu (tj. również przed akceptacją)

2023-12-28 14:18 UTC, lgpawel requested changes
Wygląda na to, że działa, z jednym zgrzytem: jeśli (zapewne słusznie) przed akceptacją tematu studenci mają nie mieć możliwości wyświetlenia tekstu deklaracji do wydrukowania, to nie powinno też się im wyświetlać linków do nich (tylko po to, żeby zaraz cisnąć im w twarz informacją o braku uprawnień). Ale tę poprawkę należy wprowadzić w drugiej kolejności, m.in. dlatego, że jej szczegóły mogą być zależne od innych, nieco bardziej fundamentalnych zmian.

Jak widać w obecnym stanie tego PRa, koncepcyjnie jedna zmiana wymaga odzwierciedlenia w dwóch różnych miejscach w kodzie: raz na potrzeby widoku "wszystkich" tematów, a raz – pojedynczego. To oczywiście jest niefortunne, łamie np. zasadę DRY itp. i warto pomyśleć, jak tego uniknąć.

Pewien pomysł (ale mam spore wątpliwości, czy najbardziej elegancki) jest taki, żeby `Q`-wyrażenie stanowiące część filtra w `ThesesQuerySet.visible` umieścić gdzieś indziej (w nowej funkcji w `theses/users.py`, której argumentem byłby tylko `user`?  a może jednak jako statyczną metodę modelu/klasy `Thesis`?), a potem korzystać z niego i w tej metodzie, i w widoku `view_thesis`. Pewnie warto też rozejrzeć się, czy jest coś bardziej idiomatycznego dla Django; przecież stosowanie (potencjalnie skomplikowanego) warunku boolowskiego zarówno w filtrowaniu `QuerySet`ów jak i dla pojedynczej instancji modelu nie brzmi jak coś niszowego.

2024-03-07 19:50 UTC, Ph0enixKM commented
Nie wiem czy do końca rozumiem co Pan sugeruje, ale przeczytałem właśnie moje zmiany po krótkiej przerwie i wydaje mi się, że ujednolicenie tutaj kodu będzie nadinżynierią, ponieważ tutaj zamiast:
- sprawdzić po ID dany Thesis
- wykonać kilka pomniejszych kwerend booleanowskich
będziemy:
- pobierać listę wszystkich prac dyplomowych 
- wykonywać operacje boolowskie na tych ściągniętych danych

Myślę, że bezpośrednie operowanie na konkretnym ID i wykonanie kilku prostych zapytań booleanowskich jest znacznie szybsze i bardziej efektywne niż przetwarzanie i filtrowanie całej listy prac dyplomowych, zwłaszcza gdy rozmiar danych zacznie rosnąć.

2024-04-05 13:36 UTC, Ph0enixKM commented on zapisy/apps/theses/views.py
> +    )
@lgpawel Ta część kodu niestety nadal musi zostać ze względu na to, że z jakiegoś powodu potrzebujemy tej informacji na frontendzie w linijce 131 przed zmianami:

```
'can_see_remarks': user_privileged_for_thesis,
```

Może zrobić zadanie by to poprawić w osobnym issue? Można niby nadal tutaj, ale musiałbym się bardziej wgryźć w sam frontend. Może omówimy to na najbliższym spotkaniu?

2024-05-17 10:21 UTC, lgpawel commented on zapisy/apps/theses/views.py
> +    )
To jest zmiana w formatowaniu kodu, więc można by ją wycofać – ale zamiast tego zróbmy z tego metodę modelu `Thesis`, bo dokładnie taki sam kawałek kodu pojawia się w kolejnej funkcji w tym module i można to zdeduplikować.

2024-05-17 10:23 UTC, lgpawel commented on zapisy/apps/theses/views.py
> +    )
Swoją drogą ta metoda będzie wtedy jedynym wystąpieniem innej, `is_among_advisors`...

2024-05-17 10:37 UTC, lgpawel commented
Zdaje się że po zmianach pojawi się jeden niepożądany (choć drobny) scenariusz; student widzący "swój" temat jeszcze przed akceptacją może kliknąć link do deklaracji przygoto(wy)wania pracy, po czym dostanie w twarz `PermissionDenied`. Trzeba więc ujednolicić zmienne `can_download_declarations` i `user_allowed_to_generate` w tych dwóch metodach, zarówno co do semantyki, jak i nazwy – i znowu, skoro pojawia się to dwa razy, to niech będzie metodą `Thesis`.

Proszę jeszcze zastanowić się, czy nie pojawia się jeszcze jakieś zachowanie tego typu.

2024-06-07 14:58 UTC, Ph0enixKM commented
@lgpawel Usunąłem zmienną `user_privileged_for_thesis` w `gen_form`, która oryginalnie była używana, ale po refaktorze nie jest ona potrzebna, ponieważ przechowywała ona jedynie wartość pośrednią, która jest już teraz obliczana wewnątrz funkcji dla zmiennej poniżej (`user_allowed_to_generate`).

2024-06-08 16:24 UTC, lgpawel commented on zapisy/apps/theses/models.py
> +    def is_user_privileged_for_thesis(self, user):
Wydaje mi się, że to się rozumie samo przez się.
```suggestion
    def is_user_privileged(self, user):
```

2024-06-08 16:26 UTC, lgpawel commented on zapisy/apps/theses/models.py
> +    def is_user_allowed_to_generate_declarations(self, user):
Oczywiście fajnie jest nazywać takie metody od `is_` ale może możemy odejść od tej zasady dla zwięzłości? (To **nie** jest pytanie retoryczne.)
```suggestion
    def can_user_generate_declarations(self, user):
```

2024-06-08 16:33 UTC, Ph0enixKM commented on zapisy/apps/theses/models.py
> +    def is_user_privileged_for_thesis(self, user):
Jak najbardziej

2024-06-08 16:34 UTC, Ph0enixKM commented on zapisy/apps/theses/models.py
> +    def is_user_allowed_to_generate_declarations(self, user):
Jasna sprawa

2024-06-08 16:38 UTC, lgpawel commented on zapisy/apps/theses/models.py
> +        return self.is_student_assigned(user) or self.user_privileged_for_thesis(user) or self.has_been_accepted
W tej chwili ten warunek jest łatwiej spełnić, niż którykolwiek z dwóch obecnie istniejących, które nim zastępujemy – np. w sytuacji, kiedy temat jest już zaakceptowany, to status/tożsamość użytkownika jest bez znaczenia.

Gdyby zrobić
```suggestion
        return self.user_privileged_for_thesis(user) or (self.has_been_accepted and self.is_student_assigned(user))
```
to byłoby chyba dokładnie tak samo, jak teraz w `gen_form`. Zastępowane wyrażenie z `view_thesis` jest pozornie mniej restrykcyjne, bo nie ma tam koniunkcji z `self.has_been_accepted`, ale do tej pory niezaakceptowany temat nie był wyświetlany jego studentowi (więc cała podstrona nie była widoczna), a to właśnie zmieniamy i również tam chyba taki kształt tego warunku będzie dobry.

2024-06-08 16:40 UTC, lgpawel commented on zapisy/apps/theses/views.py
> +    user_allowed_to_generate = thesis.is_user_allowed_to_generate_declarations(request.user)
```suggestion
    if not thesis.is_user_allowed_to_generate_declarations(request.user):
```
z usunięciem kolejnego wiersza.

2024-06-08 17:01 UTC, lgpawel commented on zapisy/apps/theses/models.py
> +    def can_user_generate_declarations(self, user):
```suggestion
    def can_user_download_declarations(self, user):
```
Raz używamy jednego, raz drugiego czasownika, i o ile ja bym nieznacznie wolał `generate`, to łatwiej się go pozbyć z tej nazwy (i odwołań do niej).

2024-06-08 17:02 UTC, lgpawel commented on zapisy/apps/theses/views.py
>      can_vote = thesis.is_voting_active and board_member
Użyta zmienna zrobiła się już trochę niepotrzebna i można się pozbyć jej deklaracji.
```suggestion
    can_vote = thesis.is_voting_active and is_theses_board_member(request.user)
```

2024-06-11 18:40 UTC, lgpawel commented on zapisy/apps/theses/models.py
> +        return self.user_privileged_for_thesis(user) or (self.has_been_accepted and self.is_student_assigned(user))
Oh come on
```suggestion
        return self.is_user_privileged(user) or (self.has_been_accepted and self.is_student_assigned(user))
```

2024-06-12 08:32 UTC, Ph0enixKM commented on zapisy/apps/theses/views.py
>      can_vote = thesis.is_voting_active and board_member
Zmienna `board_member` jest nadal używana w warunku `if` ok. 40 linii niżej

2024-06-14 12:01 UTC, Ph0enixKM commented
Plik `models.py`:

- Dodano metodę `is_user_privileged`: Sprawdza, czy użytkownik ma uprzywilejowany dostęp.
- Dodano metodę `can_user_download_declarations`: Sprawdza czy użytkownik może pobrać deklaracje.
- Zaktualizowano filtr `ThesesQuerySet.visible`: Przypisani studenci mogą również mieć dostęp do pracy.

Plik `views.py`:

- Wszędzie gdzie jest `get_object_or_404(Thesis, id=id)` używamy teraz metodę `ThesesQuerySet.visible`
- Usunięcie zmiennej `user_privileged_for_thesis`: Nie jest już potrzebna jako, że ta wartość pośrednia jest obliczana w nowych metodach
- Usunięcie `if not thesis.has_been_accepted and not user_privileged_for_thesis:` ponieważ to już nam zapewnia filtr `ThesesQuerySet.visible`
- `user_privileged_for_thesis` oraz `user_allowed_to_generate` zostało również usunięte ze względu na to, że również są te wartości obliczane w nowych metodach

2024-06-15 09:02 UTC, merged