System Zapisów Deployment
iiuni/projektzapisy pull request #933
Opened 2020-07-06 19:06 UTC by barnij

PR dodaje skrypty i usługi, które w łatwy sposób pozwalają wykonać deploy Systemu Zapisów na zdalnej maszynie opartej o system Ubuntu. 

Skrypty zostały napisane jako playbooki programu ansible i możemy je podzielić na trzy części:
1. Konfiguracja maszyny
2. Deployment
3. Przywrócenie bazy danych

Do zmian dołączona została także [instrukcja](https://github.com/iiuni/projektzapisy/blob/ansible-deploy/ansible/deploy/readme.md).

To do:
- Automatyczne kopie bazy danych

2020-07-09 15:00 UTC, jasiekmarc commented on ansible/deploy/.env
> +PIPELINE=False
To jest potrzebne?

2020-07-09 15:08 UTC, jasiekmarc commented on ansible/deploy/.env
> +ALLOWED_HOSTS=*
To chyba nie powinna być gwiazdka. To powinien być host maszyny zapewne (np. `zapisy.ii.uni.wroc.pl`).

2020-07-09 21:08 UTC, barnij commented on ansible/deploy/configure.yml
> +      become: yes
@receek ?

2020-07-09 21:45 UTC, barnij commented on ansible/deploy/backup.service
> +WantedBy=default.target
Hmmm, wydaje mi się, że nie. Tej usłudze nie przypisujemy "enabled". Ją uruchamia tylko timer.

2020-07-09 21:50 UTC, barnij commented on ansible/deploy/configure.yml
> +          - django-environ==0.4.5
1. W przykładach użyte są podwojone znaki równości - [link](https://docs.ansible.com/ansible/latest/modules/pip_module.html)
2. To są moduły używane do backupu i zainstalowane jako użytkownik zapisy. Nie mogą być w _requirements_, instalowane razem z innymi modułami w _virtualenv'ie_, bo to by oznaczało, że bez obecnego choć jednego sprawnego deployu, nie moglibyśmy zrobić kopii bazy danych.

2020-07-09 21:57 UTC, barnij commented on ansible/deploy/readme.md
> +    where `user` is your username on the remote machine
Naprawdę lepiej? I tak trzeba wpisać tę grupę do pliku, a dodatkowo ją stworzyć i dodać do niej użytkownika. 
Nie jest też wcale dużo szybciej przy następnym użytkowniku na tej samej maszynie, bo dla niego ponownie musimy skonfigurować ssh i też dodać go do tej grupy.

2020-07-09 21:58 UTC, barnij commented on ansible/deploy/readme.md
> +`hosts` is inventory file like above.
Tak, chyba nie byłoby z tym dużo roboty

2020-07-09 21:59 UTC, barnij commented on ansible/deploy/.env
> +PIPELINE=False
Że `PIPELINE`?

2020-07-09 22:10 UTC, barnij commented on ansible/deploy/configure.yml
> +      become: yes
Wersja z gwiazdką również jest podana w przykładach w dokumentacji. 
Problemem może być fakt, że `upgrade: full` korzysta z aptitude, a nie apt-get - [link](https://docs.ansible.com/ansible/latest/modules/apt_module.html):
> If full, performs an aptitude full-upgrade. 

A pamiętam, że czasami potrafił rzucać błędami, gdy nie korzystało się z apt-get.

2020-07-10 08:47 UTC, jasiekmarc commented on ansible/deploy/.env
> +PIPELINE=False
Mhm. Z Pipeline'm żeśmy się już pożegnali w #856.

2020-07-10 08:49 UTC, jasiekmarc commented on ansible/deploy/backup.service
> +WantedBy=default.target
No dobrze. Ale semantycznie to chyba nie jest poprawne?

2020-07-10 08:50 UTC, jasiekmarc commented on ansible/deploy/configure.yml
> +      become: yes
> Note: Since 2.4, apt-get is used as a fall-back if aptitude is not present.

Ale może Pan dodać `force_apt_get: true`

2020-07-10 08:56 UTC, jasiekmarc commented on ansible/deploy/readme.md
> +    where `user` is your username on the remote machine
Naprawdę lepiej.
Grupy są właściwą metodą sterowania uprawnieniami. Podam abstrakcyjny scenariusz, który jest nieprawdopodobny ale powinien obrazować problem:
1. Tworzymy użytkownika `zenek`, który ma być administratorem. Zgodnie z Pana instrukcją dodajemy go do pliku _sudoers_.
2. Zenek przestaje u nas pracować, usuwamy mu konto. Oczywiście nie pamiętamy o pliku.
3. Przychodzi jakiś inny zenek, który nie ma być administratorem. Tworzymy mu konto. Przez pomyłkę może robić na maszynie wszystko, bo ten stary zenek jest w pliku _sudoers_.

2020-07-10 09:01 UTC, jasiekmarc commented on ansible/deploy/configure.yml
> +          - django-environ==0.4.5
`==` znaczy, że chce Pan dokładnie taką wersję. Jeśli Dropbox wrzuci nową, kompatybilną, wersję paczki, w której zamieści ważną poprawkę luki bezpieczeństwa, my się na nią nie załapiemy. `~=` znaczy „daj mi najnowszą kompatybilną wersję paczki:
https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean

Natomiast w tej drugiej kwestii, jeśli nie mamy wersji `current` kodu, to i tak się nam ten backup nie odpali.

2020-07-10 09:05 UTC, jasiekmarc commented on ansible/deploy/deploy.yml
> +    - name: Finalize the deploy, removing the unfinished file and switching the symlink
Tu jeszcze potrzebujemy informowania Rollbara o skutecznym deploy'u.
https://docs.ansible.com/ansible/latest/modules/rollbar_deployment_module.html

Tak jak się to teraz dzieje. Rollbar dzięki temu śledzi, w jakiej wersji kodu pojawiają się błędy. Przy okazji Rollbar następnie wrzuca info na Slacka (na kanał `#bugs`).

2020-07-10 14:59 UTC, receek commented on ansible/deploy/configure.yml
> +      become: yes
Źródła podają, że plik usługi zdefiniowany w `/etc/systemd/system` ma pierwszeństwo nad innymi lokalizacjami usług w systemie oraz, że menadżer pakietów aktualizuje plik usługi tylko w obrębie `/usr/lib/systemd/system`.  Zatem w tej sytuacji aktualizacja Nginx-a nie ma wpływu na jego plik usługi.

2020-07-10 15:08 UTC, receek commented on ansible/deploy/configure.yml
> +      become: yes
Myślę, że to nie byłoby złym pomysłem ale należy mieć na uwadze, że przyszłościowe wersje Nginx-a mogą wnosić zmiany w podstawowy plik usługi.

2020-07-10 21:16 UTC, jasiekmarc commented on ansible/deploy/configure.yml
> +      become: yes
Szczerze mówiąc po tak poważnym narzędziu jak Nginx nie spodziewałbym się niekompatybilnych wstecznie zmian. A już na pewno ich nie będzie w stabilnej wersji Ubuntu.

2020-07-10 21:20 UTC, jasiekmarc commented on ansible/deploy/configure.yml
> +      become: yes
Szczerze mówiąc po tak poważnym narzędziu jak Nginx nie spodziewałbym się niekompatybilnych wstecznie zmian. A już na pewno ich nie będzie w stabilnej wersji Ubuntu.

---
Sorry, ta odpowiedź miała być tu.

2020-07-17 17:22 UTC, barnij commented on ansible/deploy/deploy.yml
> +    - name: Enable and run rqworker1 service
A która jest która?

2020-07-19 23:09 UTC, barnij commented on ansible/deploy/configure.yml
> +        regexp: '\$num_proc\$'
Chyba nie za bardzo rozumiem jak miałoby to być użyte

2020-07-19 23:10 UTC, barnij commented on ansible/deploy/ssl/nginx-selfsigned.crt
> +-----BEGIN CERTIFICATE-----
To prawda, ale rozumiem, że generować chcemy je tylko wtedy jeśli administrator nam ich nie dostarczył? Tzn. na przykład pusty jest katalog ssl

2020-07-20 10:02 UTC, jasiekmarc commented on ansible/deploy/configure.yml
> +        regexp: '\$num_proc\$'
https://docs.ansible.com/ansible/latest/modules/template_module.html#template-module

2020-07-20 10:03 UTC, jasiekmarc commented on ansible/deploy/ssl/nginx-selfsigned.crt
> +-----BEGIN CERTIFICATE-----
W moim przekonaniu, w nowej maszynie powinno być wygenerowane, bo to nic nie kosztuje. A jak administrator dostanie certyfikaty, to może je — posługując się instrukcją — przekopiować.

2020-08-15 19:00 UTC, barnij commented on ansible/deploy/production
> +[deploy:children]
Chcemy przenosić folder _env_?

2020-08-15 19:39 UTC, jasiekmarc commented on ansible/deploy/production
> +[deploy:children]
Wszystko jedno

2020-09-04 11:25 UTC, jasiekmarc requested changes
Przetestowałem i wszystko ładnie działa. Zostało parę drobnostek i będziemy merge'ować.

2020-09-04 11:25 UTC, jasiekmarc commented on infra/readme.md
> +	- `deploy-version` - name of branch from __projektzapisy__ repository
```suggestion
	- `deploy_version` - name of branch from __projektzapisy__ repository
```

2020-09-04 11:25 UTC, jasiekmarc commented on infra/readme.md
> +- `systemctl status example.service` - shows the status of example service
Proponuję, żeby do folderu `hosts/` dodać pliki
_Vagrantfile_
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Fix Ubuntu Focal box issue: https://bugs.launchpad.net/cloud-images/+bug/1829625
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
end
```
oraz _example_
```
[deploy:children]
server1

[deploy:vars]
deploy_env=staging

[server1]
webserver1

[server1:vars]
ansible_host=192.168.33.10
ansible_port=22
ansible_user=vagrant
ansible_ssh_private_key_file=hosts/.vagrant/machines/default/virtualbox/private_key
deploy_user=zapisy
deploy_version=master-dev
deploy_server_name=192.168.33.10
rollbar_token=none
```

Tutaj natomiast, żeby dodać sekcję `## Example` z instrukcją użycia.
W skrócie:
- Wejść do `hosts/`, zrobić `vagrant up`.
- Przeskoczyć do `infra/` zrobić `ansible-playbook playbooks/configure.yml -i hosts/example` i tak dalej…

Dzięki temu naprawdę łatwo można sobie to przetestować na swoim komputerze.

2020-09-04 11:25 UTC, jasiekmarc commented on infra/readme.md
> +2. Create group `zapisy-admin`: `sudo groupadd zapisy-admin`
Wydaje mi się, że lepiej do tego użyć już istniejącej grupy `adm`. Nie trzeba jej tworzyć, tylko w kroku 4 trzeba jej zmodyfikować konfigurację.

2020-09-04 11:25 UTC, jasiekmarc commented on infra/readme.md
> +To display additional information during configuration, deployment, or restoring database add the flag `-vvv` to ansible-playbook commands.
Odkryłem, że ustawienie zmiennej środowiskowej `ANSIBLE_STDOUT_CALLBACK=debug` daje czytelniejszy output. Warto tu to napisać.

2020-09-04 11:25 UTC, jasiekmarc commented on infra/db_backups/requirements.txt
> +slackclient==2.7.2
Ten plik chyba może zniknąć już?

2020-09-05 09:25 UTC, jasiekmarc approved these changes

2020-09-05 10:16 UTC, merged