Remove redundant tables #857
iiuni/projektzapisy pull request #993
Opened 2020-10-08 16:10 UTC by Konrad-Kasprzyk

2020-10-08 20:24 UTC, jasiekmarc requested changes

2020-10-08 20:24 UTC, jasiekmarc commented on zapisy/apps/schedulersync/migrations/0004_delete_redundant_tables.py
> +# Generated by Django 3.0.10 on 2020-10-08 15:41
Mógłbym jeszcze prosić tutaj o komentarz?

Ta migracja nie ma nic wspólnego z aplikacją Schedulersync, i gdyby ktoś się tu zabłąkał, to warto go o tym poinformować.

2020-10-13 12:26 UTC, Konrad-Kasprzyk commented on zapisy/apps/schedulersync/migrations/0004_delete_redundant_tables.py
> +# Generated by Django 3.0.10 on 2020-10-08 15:41
Zrobione

2020-10-13 12:28 UTC, jasiekmarc requested changes

2020-10-13 12:28 UTC, jasiekmarc commented on zapisy/apps/schedulersync/migrations/0004_delete_redundant_tables.py
> +# It has nothing to do with schedulersync app and it's models
Ha ha.
```suggestion
# It has nothing to do with schedulersync app and its models
```
It's = It is

2020-10-13 12:35 UTC, jasiekmarc approved these changes

2020-10-13 12:36 UTC, Konrad-Kasprzyk commented on zapisy/apps/schedulersync/migrations/0004_delete_redundant_tables.py
> +# It has nothing to do with schedulersync app and it's models
Zdarza się.

2020-10-13 13:01 UTC, merged