Fixed groups selection
iiuni/projektzapisy pull request #994
Opened 2020-10-08 18:39 UTC by whiskeyo

Related issue: #988

2020-10-10 15:55 UTC, jasiekmarc commented
Nie rozumiem tego PR-a. Czy on naprawia issue #988?

W opisie Pull Requesta zawsze musi być wyjaśnienie, jaki problem jest rozwiązywany i w jaki sposób.

2020-10-12 18:49 UTC, jasiekmarc requested changes
Dziękuję bardzo za przygotowanie PR-a. Pozwoliłem sobie zmienić opis na bardziej klarowny. Zostawiłem też 2 komentarze.

2020-10-12 18:49 UTC, jasiekmarc commented on zapisy/apps/enrollment/timetable/views.py
> +        Q(teacher__user=request.user) | Q(record__student__user=request.user), Q(record__status='1'))
To trochę śmierdzi. Nie wiem, czy wynik tego zapytania jest poprawny, ale są tu dwie podejrzane rzeczy.
1. Semantyka. Nie wiem, czy przecinek łączy bardziej niż `|`. Jest jasne, że chcemy tu mieć alternatywę dwóch warunków — jeden to `teacher__user=request.user`, a drugi to ten odpowiadający studentowi. Dlatego używamy `models.Q` i łączenia `|`. Do jednego `models.Q` można wsadzić dwa warunki oddzielone przecinkiem, co działa jak `AND`.
2. Nigdy nie porównujemy z ręcznie napisanymi stałymi, takimi jak `'1'`. Taki kod jest nieczytelny (co to znaczy `'1'`?) i niesamowicie trudny do prześledzenia (np. proszę mi znaleźć wszystkie miejsca w projekcie, gdzie pytamy o zapisanych studentów). Importujemy `RecordStatus` i piszemy `RecordStatus.ENROLLED`.

2020-10-12 18:49 UTC, jasiekmarc commented on zapisy/apps/schedule/models/term.py
> +        else:
W Pythonie jest konstrukcja
```python
for x in xs:
    ...
else:
    ...
```
która niestety robi coś zupełnie innego, niż byśmy chcieli :grinning: 

Wydaje mi się jednak mimo wszystko, że naturalniejsze byłoby napisanie
```python
for room in rooms:
    ...
if not rooms:
    ...
```
albo ewentualnie (gdyby pan chciał być sprytny)
```py
for room in rooms or [None]:
    ...
```

**EDIT**: To ostatnie można by zastosować wyżej, przy przypisaniu do `rooms`. To by było bardziej czytelne.

2020-10-12 21:29 UTC, whiskeyo commented on zapisy/apps/enrollment/timetable/views.py
> +        Q(teacher__user=request.user) | Q(record__student__user=request.user), Q(record__status='1'))
Z góry założyłem, że `AND` jest bardziej wiążący niż `OR`, tak jak mówią zasady logiki. Poprawiłem to query w następnym commicie, aby było bardziej czytelne. Błąd porównania statusu rekordu również zmieniłem, dzięki czemu wiadomo już o co dokładnie chodzi.

2020-10-12 21:37 UTC, whiskeyo commented on zapisy/apps/schedule/models/term.py
> +        else:
W najnowszym commicie użyłem jednego z Pana rozwiązań, jednak mam wrażenie, że nie różni się ono bardzo od mojego - użyłem tam konstrukcji opisanej niżej, a nie `for ... else ...`.
```python
if not rooms:
    ...
else:
    for room in rooms:
        ...
```

2020-10-13 08:13 UTC, jasiekmarc commented on zapisy/apps/schedule/models/term.py
> +        else:
Dobrze, teraz jest lepiej niż było.
> [Flat is better than nested.](https://en.wikipedia.org/wiki/Zen_of_Python)

2020-10-13 08:25 UTC, jasiekmarc approved these changes

2020-10-13 08:27 UTC, jasiekmarc commented
@matpyz Po deploy'u zawierającym tę zmianę będzie trzeba powiedzieć aplikacji, żeby wygenerowała te termy poprawnie.
Instrukcje autor umieścił tutaj: https://github.com/iiuni/projektzapisy/issues/988#issuecomment-707240704

2020-10-13 08:27 UTC, merged