Changes in models group.py and records.py
iiuni/projektzapisy pull request #999
Opened 2020-10-25 00:38 UTC by alekstrolo

Review

2020-10-26 12:42 UTC, jasiekmarc requested changes
Tytuł i opis Pull Requesta powinny mówić o tym, jaki problem jest rozwiązywany i w jaki sposób. Można opowiedzieć, na jakie się natrafiło trudności i jak się je rozwiązało. W ten sposób, gdyby ktoś w przyszłości napotkał jakiś problem, łatwo zorientuje się, o co chodziło.
Pan napisał w tytule, w jakich plikach zrobił zmiany (co można zobaczyć w diffie). W opisie zaś stoi: „Review”.

Proszę to ładnie poprawić.

2020-10-26 12:42 UTC, jasiekmarc commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
Ta funkcja nie ma sensu. 
```
group.get_type_display()
```
automatycznie daje to, co próbuje robić ta funkcja (tylko że ta się zdeaktualizowała).
Trzeba wywalić ją i poprawić miejsca, w których jest użyta.

2020-10-26 12:42 UTC, jasiekmarc commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
Trzeba też zaktualizować albo — najlepiej — usunąć _template tagi_ zdefiniowane tutaj:
https://github.com/iiuni/projektzapisy/blob/master-dev/zapisy/apps/enrollment/courses/templatetags/course_types.py

2020-10-30 08:06 UTC, alekstrolo commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
Nie chcemy mieć przedmiotów w licznie mnogiej na stronie?

2020-10-30 11:13 UTC, jasiekmarc commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
Nie wiem. Jeśli jest to niezbędne, to pewnie chcemy.

2020-11-06 08:05 UTC, alekstrolo commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
zrobione

2020-11-06 08:07 UTC, alekstrolo commented on zapisy/apps/enrollment/courses/models/group.py
>      def human_readable_type(self):
Sprawdziłem, metody są potrzebne dla czytelności strony, więc zupdatowałem.
Zupowałem repozytorium do mastera, żeby sprawdzić czy są konflikty i widzę, że w commitach teraz są też te z mastera które były robione w międzyczasie. Moje nowe to 4 ostatnie.

2020-11-10 12:43 UTC, jasiekmarc commented
Autor zduplikował tego PR-a do #1004.

2020-11-10 12:43 UTC, closed without merging